package-lock.json
packages/deployer/package.json
packages/deployer/subtasks/prepare-deployment.js
packages/deployer/subtasks/sync-sources.js
packages/deployer/task-names.js
packages/deployer/tasks/deploy.js
packages/deployer/utils/autosave-object.js
packages/deployer/utils/relative-path.js

This PR adds the subtask for syncing the deployment file, and notifies of deletions and additions on new deployment.

Add sync sources subtask

---

package-lock.json
packages/deployer/package-lock.json
packages/deployer/test/sample-project/contracts/modules/UpgradeModule.sol
packages/deployer/test/sample-project/contracts/storage/ProxyNamespace.sol

Adds a new anti-bricking mechanism that tryies to do a rollback after upgrading and if it fails the upgrade is reverted.

Add anti-bricking mechanism to UpgradeModule

---

.gitignore
packages/deployer/.gitignore
packages/deployer/subtasks/deploy-router.js
packages/deployer/subtasks/generate-router.js
packages/deployer/subtasks/validate-router.js
packages/deployer/task-names.js
packages/deployer/tasks/deploy.js
packages/deployer/templates/Router.sol.template
packages/deployer/test/sample-project/package.json
packages/deployer/utils/contracts.js

This PR generates the updated Router using the modules defined on the deployments file and deploys it if necessary.

Add router generation & deployment subtasks

---

package-lock.json
packages/deployer/subtasks/generate-router.js

Throw when duplicate selectors are found

---

packages/deployer/extensions/environment.js
packages/deployer/subtasks/clear-deployments.js
packages/deployer/subtasks/deploy-router.js
packages/deployer/subtasks/generate-router.js
packages/deployer/subtasks/prepare-deployment.js
packages/deployer/subtasks/upgrade-proxy.js
packages/deployer/subtasks/validate-router.js
packages/deployer/tasks/deploy.js
packages/deployer/utils/deployments.js
packages/deployer/utils/router.js

Stop using hre.deployer.paths

---

packages/deployer/extensions/config.js
packages/deployer/extensions/environment.js
packages/deployer/subtasks/generate-router.js

Move routerTemplate to env

---

packages/core-js/utils/contracts.js
packages/deployer/subtasks/deploy-contract.js
packages/deployer/subtasks/generate-router.js
packages/deployer/subtasks/validate-router.js
packages/deployer/utils/contracts.js

split contracts

---

.solhint.json

Add rule to limit error msg length

---

packages/deployer/internal/ast/ast-helper.js
packages/deployer/internal/ast/router-ast-validator.js
packages/deployer/internal/ast/router-validator.js
packages/deployer/internal/contract-helper.js
packages/deployer/internal/router-source-validator.js
packages/deployer/subtasks/validate-router.js
packages/deployer/tasks/deploy.js
packages/deployer/test/sample-project/contracts/modules/AnotherModule.sol

Validate Router via code + AST

---

packages/deployer/internal/ast/ast-helper.js
packages/deployer/internal/ast/storage-validator.js
packages/deployer/subtasks/validate-modules.js
packages/deployer/subtasks/validate-storage.js

Checks for state variable declarations in modules

---

packages/deployer/internal/ast/ast-helper.js
packages/deployer/internal/ast/router-ast-validator.js
packages/deployer/internal/router-helper.js
packages/deployer/subtasks/generate-router.js
packages/deployer/subtasks/validate-router.js

Add Router Validations

---

packages/core-contracts/test/proxy/ForwardingProxy.test.js
packages/deployer/internal/contract-helper.js
packages/deployer/internal/process-contracts.js

Fixes the lookup of source files for the given contract when saving the source on deployments files.

Fix lookup for contract source

---

packages/core-contracts/contracts/mocks/proxy/ForwardingProxyMock.sol
packages/core-contracts/contracts/mocks/proxy/ImplementationMockA.sol
packages/core-contracts/contracts/mocks/proxy/ImplementationMockB.sol
packages/core-contracts/contracts/proxy/ForwardingProxy.sol
packages/core-contracts/test/proxy/ForwardingProxy.test.js
packages/deployer/internal/contract-helper.js
packages/deployer/internal/process-contracts.js
packages/deployer/test/sample-project/contracts/Proxy.sol

Implements basic proxy in core-contracts

---

packages/deployer/test/sample-project/contracts/mixins/OwnerMixin.sol
packages/deployer/test/sample-project/contracts/modules/OwnerModule.sol
packages/deployer/test/sample-project/contracts/modules/SettingsModule.sol
packages/deployer/test/sample-project/contracts/modules/SomeModule.sol

Remove v2x type comments

---

packages/deployer/subtasks/finalize-deployment.js

Fix #186 
Fix on the fly while debugging. We were deleting only the main deployment file and missing the extended ones.

Delete missing temp files

---

packages/core-contracts/contracts/mocks/token/ERC20Mock.sol
packages/core-contracts/contracts/ownership/Ownable.sol
packages/core-contracts/contracts/ownership/OwnableMixin.sol
packages/deployer/subtasks/validate-router.js
packages/deployer/test/fixture-projects/sample-project/contracts/mixins/OwnerModuleMixin.sol
packages/deployer/test/fixture-projects/sample-project/test/UpgradeModule.test.js

fix #216 
Re-enable findUnreachableModuleSelectors(). It was already fixed on main. 
+ some linting

re-enable findUnreachableModuleSelectors()

---

packages/core-contracts/contracts/mocks/token/ERC20Mock.sol
packages/core-contracts/contracts/token/ERC20.sol

Fix #227
@i-stam was there anything else that we needed to do here?

Minor changes to ERC20

---

packages/deployer/test/fixture-projects/sample-project/contracts/Proxy.sol
packages/deployer/test/fixture-projects/sample-project/contracts/mixins/CommsMixin.sol
packages/deployer/test/fixture-projects/sample-project/contracts/mixins/OwnerMixin.sol
packages/deployer/test/fixture-projects/sample-project/contracts/mocks/Destroyer.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/OwnerModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/SettingsModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/SomeModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/UpgradeModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/GlobalStorage.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/OwnerStorage.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/ProxyStorage.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/SettingsStorage.sol
packages/deployer/test/fixture-projects/sample-project/test-contracts/NewModule.sol
packages/deployer/test/fixture-projects/sample-project/test-contracts/SomeModule.modified.sol
packages/synthetix-main/contracts/Proxy.sol
packages/synthetix-main/contracts/storage/ProxyStorage.sol

Suggesting a change of naming convention

---

package-lock.json
packages/core-contracts/contracts/mocks/proxy/ForwardingProxyMock.sol
packages/core-contracts/contracts/proxy/ForwardingProxy.sol
packages/deployer/test/fixture-projects/sample-project/contracts/Proxy.sol
packages/synthetix-main/contracts/Proxy.sol

FIX #249 
This PR removes the constructor from the ForwardingProxy core-contract.

Remove ForwardingProxy constructor

---

packages/core-contracts/contracts/proxy/UniversalProxyImplementation.sol

Use encodeWithSelector instead of encodeWithSignature

---

packages/deployer/test/src/internal/argument-types.test.js

Add test to argument-types.js

---

.github/workflows/test.yml

add run CI tests on sample project

---

packages/core-js/utils/events.js
packages/synthetix-main/test/SNXModule.test.js

Bring synthetix-main tests back

---

packages/core-contracts/contracts/ownership/Ownable.sol
packages/core-contracts/contracts/ownership/OwnableMixin.sol
packages/core-contracts/contracts/ownership/OwnableStorage.sol
packages/core-contracts/contracts/proxy/Beacon.sol
packages/core-contracts/contracts/proxy/BeaconProxy.sol
packages/core-contracts/contracts/proxy/BeaconStorage.sol
packages/core-contracts/contracts/proxy/ProxyStorage.sol
packages/core-contracts/contracts/proxy/UUPSImplementation.sol
packages/core-contracts/contracts/proxy/UUPSProxy.sol
packages/core-contracts/contracts/token/ERC20.sol
packages/core-contracts/contracts/token/ERC20Storage.sol
packages/core-modules/contracts/test/modules/UpgradeModuleMock.sol
packages/deployer/test/fixture-projects/sample-project/contracts/mixins/CommsMixin.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/SettingsModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/SomeModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/GlobalStorage.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/SettingsStorage.sol
packages/deployer/test/fixture-projects/sample-project/contracts/test/Destroyer.sol
packages/deployer/test/fixture-projects/sample-project/test-contracts/NewModule.sol
packages/deployer/test/fixture-projects/sample-project/test-contracts/SomeModule.modified.sol
packages/synthetix-main/contracts/modules/SNXTokenModule.sol
packages/synthetix-main/contracts/storage/SNXTokenStorage.sol

Namespace rename

---

packages/core-contracts/contracts/test/proxy/ImplementationMockB.sol
packages/core-contracts/test/contracts/proxy/UUPSProxy.test.js

Added payable tests to UUPSProxy

---

packages/core-contracts/contracts/test/token/ERC20Mock.sol
packages/core-contracts/contracts/token/ERC20.sol
packages/core-contracts/test/contracts/token/ERC20.test.js

Replace constructor by initilize in ERC20

---

packages/synthetix-main/.solcover.js
packages/synthetix-main/contracts/mocks/token/SNXTokenMock.sol
packages/synthetix-main/contracts/modules/SNXTokenModule.sol
packages/synthetix-main/test/contracts/modules/SNXModule.test.js

SNXToken to implement ERC20

---

packages/core-modules/contracts/test/modules/CoreUpgradeModuleMock.sol
packages/core-modules/test/contracts/modules/CoreUpgradeModule.test.js
packages/synthetix-main/contracts/modules/UpgradeModule.sol
packages/synthetix-main/test/contracts/modules/SNXTokenModule.test.js
packages/synthetix-main/test/contracts/modules/UpgradeModule.test.js
packages/synthetix-main/test/helpers/bootstrap.js

Make synthetix-main upgradable

---

packages/core-contracts/contracts/mocks/proxy/ImplementationDestroyer.sol
packages/core-contracts/contracts/mocks/proxy/SterileImplementation.sol
packages/core-contracts/test/contracts/proxy/UUPSProxy.test.js

Add tests for bricking the proxy

---

packages/synthetix-main/contracts/interfaces/ISynth.sol
packages/synthetix-main/contracts/mocks/token/SynthMock.sol
packages/synthetix-main/contracts/modules/SynthsModule.sol
packages/synthetix-main/contracts/token/Synth.sol
packages/synthetix-main/test/contracts/modules/SynthsModule.test.js

Synths contract  and initialization on deployment

---

packages/core-contracts/test/contracts/ownership/Ownable.test.js
packages/core-modules/test/contracts/modules/CoreOwnerModule.test.js
packages/core-modules/test/contracts/modules/CoreUpgradeModule.test.js
packages/deployer/test/fixture-projects/sample-project/test/SomeModule.test.js
packages/deployer/test/helpers.js

Clean up hre imports

---

packages/core-contracts/test/contracts/token/ERC20.test.js
packages/core-modules/test/contracts/modules/CommsMixin.test.js
packages/core-modules/test/contracts/modules/CoreOwnerModule.test.js
packages/core-modules/test/contracts/modules/CoreUpgradeModule.test.js
packages/core-modules/test/contracts/modules/RouterCoverage.test.js
packages/synthetix-main/test/contracts/modules/SNXTokenModule.test.js
packages/synthetix-main/test/contracts/modules/SynthsModule.test.js

Remove toNumber and parseInt from bn tests

---

packages/core-contracts/test/contracts/ownership/Ownable.test.js
packages/core-contracts/test/contracts/proxy/Beacon.test.js
packages/core-contracts/test/contracts/proxy/BeaconProxy.test.js
packages/core-contracts/test/contracts/proxy/UUPSProxy.test.js
packages/core-contracts/test/contracts/token/ERC20.test.js
packages/core-contracts/test/contracts/utils/ContractUtil.test.js
packages/core-js/utils/assert-bignumber.js
packages/deployer/test/fixture-projects/sample-project/test/contracts/SettingsModule.test.js
packages/deployer/test/fixture-projects/sample-project/test/contracts/SomeModule.test.js

Fix assert strict usage

---

packages/deployer/tasks/deploy.js

Fix quiet option when compiling contracts

---

package-lock.json
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/storage/CoreElectionStorage.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/contracts/token/MemberToken.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js
packages/synthetix-main/contracts/modules/SNXTokenModule.sol

Add election module

---

.eslintrc.js
package-lock.json
package.json

Disallow .only in tests

---

packages/core-modules/contracts/token/MemberToken.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Change MemberToken to use ERC721

---

packages/core-contracts/contracts/mocks/token/ERC721OwnedMock.sol
packages/core-contracts/contracts/token/ERC721Owned.sol
packages/core-contracts/test/contracts/token/ERC721Owned.test.js

Make-NFT-Ownable

---

packages/deployer/subtasks/deploy-contract.js
packages/deployer/subtasks/deploy-contracts.js

Confirm on deploy subtask

---

packages/deployer/internal/process-transactions.js
packages/deployer/subtasks/deploy-contract.js
packages/deployer/subtasks/upgrade-proxy.js
packages/deployer/test/unit/internal/process-transactions.test.js

Add block info to deployments

---

packages/core-contracts/contracts/token/ERC20.sol
packages/core-contracts/contracts/token/ERC721.sol
packages/core-contracts/contracts/utils/StringUtil.sol

Mention reference implementations

---

packages/core-contracts/contracts/proxy/Beacon.sol
packages/core-contracts/contracts/proxy/UUPSImplementation.sol
packages/core-contracts/contracts/proxy/UUPSProxy.sol
packages/core-contracts/test/contracts/proxy/Beacon.test.js
packages/core-contracts/test/contracts/proxy/UUPSProxy.test.js

Fix #517
Adds a couple of checks, and their corresponding errors.

Adds some checks

---

packages/core-contracts/contracts/errors/ArgumentError.sol
packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Closes #459 
This PR adds the first base for implementing elections on top. At this point, this is not a working governance module.

[PoC] Add basic council elections

---

packages/core-js/test/utils/rpc.test.js
packages/core-js/utils/rpc.js
packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Governance Epoch

---

packages/deployer/templates/Router.sol.mustache

Update router template

---

packages/synthetix-main/contracts/interfaces/ISynthsModule.sol
packages/synthetix-main/contracts/modules/SynthsModule.sol
packages/synthetix-main/test/contracts/modules/SynthsModule.test.js
packages/synthetix-main/test/contracts/modules/UpgradeModule.test.js

Small improvements to SynthsModule

---

.github/workflows/test.yml

Update run tests to matrix file

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/mocks/ElectionTokenMock.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Add elections history

---

packages/cli/subtasks/pick-parameters.js

Fix #560
Only one pre-processor implemented: Conversion of strings to bytes32 (only if needed).

Introduces input pre-processing in CLI

---

packages/deployer/subtasks/deploy-contracts.js
packages/deployer/subtasks/print-info.js
packages/deployer/subtasks/sync-sources.js
packages/deployer/tasks/deploy.js

Minor tweaks to deployer logs

---

.github/workflows/test.yml
package-lock.json
packages/cli/.mocharc.json
packages/cli/internal/signatures.js
packages/cli/package.json
packages/cli/subtasks/execute-call.js
packages/cli/subtasks/pick-function.js
packages/cli/test/fixtures/abis/sample-event-abi.js
packages/cli/test/fixtures/abis/sample-event-receipt.js
packages/cli/test/fixtures/abis/sample-function-abi.js
packages/cli/test/unit/internal/signatures.test.js

Introduces cli unit tests

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Refactor loop for checking addresses votes

---

packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Add election setup for first epoch

---

packages/core-contracts/.solcover.js
packages/synthetix-main/.solcover.js

Reduce code instrumentation size on coverage

---

packages/core-js/utils/ast/finders.js

Minor tweaks to parameter naming in AST finder util

---

packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Add the ability to cast votes again

---

.solhint.json
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol

Disable linter Solidity time rule

---

packages/core-contracts/contracts/mocks/utils/ArrayUtilMock.sol
packages/core-contracts/contracts/utils/ArrayUtil.sol
packages/core-contracts/test/contracts/utils/ArrayUtil.test.js
packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Simplify elect function

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/contracts/token/MemberToken.sol
packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
packages/core-modules/test/contracts/modules/CoreElectionModule.test.js

Shuffle NFTs 

---

packages/core-contracts/contracts/proxy/UUPSImplementation.sol

Remove unused boolean in upgrade logic

---

packages/cli/internal/signatures.js
packages/cli/scripts/test.sh
packages/cli/subtasks/pick-function.js
packages/cli/test/integration/execute-call.test.js
packages/cli/test/integration/helpers/cli-runner.js
packages/cli/test/integration/pick-contract.test.js
packages/cli/test/integration/pick-function.test.js
packages/cli/test/integration/pick-parameters.test.js
packages/cli/test/integration/print-info.test.js

More cli tests

---

packages/core-modules/contracts/modules/CoreElectionModule.sol
packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
packages/core-modules/contracts/storage/ElectionStorage.sol

Refactor election data storage

---

packages/cli/test/fixture-projects/sample-project/contracts/modules/UpgradeModule.sol
packages/core-modules/contracts/modules/OwnerModule.sol
packages/core-modules/contracts/modules/UpgradeModule.sol
packages/core-modules/test/contracts/modules/OwnerModule.test.js
packages/core-modules/test/contracts/modules/UpgradeModule.test.js
packages/core-modules/test/helpers/initializer.js
packages/deployer/internal/contract-helper.js
packages/deployer/test/fixture-projects/custom-proxy/contracts/modules/UpgradeModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/OwnerModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/UpgradeModule.sol
packages/deployer/test/fixture-projects/sample-project/test/helpers/initializer.js
packages/deployer/test/fixture-projects/sibling-contracts/contracts/modules/UpgradeModule.sol
packages/synthetix-main/contracts/modules/OwnerModule.sol
packages/synthetix-main/contracts/modules/UpgradeModule.sol
packages/synthetix-main/test/contracts/modules/UpgradeModule.test.js
packages/synthetix-main/test/helpers/initializer.js

Review naming conventions

---

packages/core-js/test/fixtures/initializable-ast.json
packages/core-js/test/utils/ast/finders.test.js
packages/core-js/utils/ast/finders.js
packages/deployer/internal/initializable-ast-validator.js
packages/deployer/subtasks/validate-initializables.js
packages/deployer/subtasks/validate-storage.js
packages/deployer/task-names.js
packages/deployer/tasks/deploy.js
packages/deployer/test/fixture-projects/inconsistent-initializable/contracts/Proxy.sol
packages/deployer/test/fixture-projects/inconsistent-initializable/contracts/modules/InitializableModule.sol
packages/deployer/test/fixture-projects/inconsistent-initializable/contracts/storage/InitializableStorage.sol
packages/deployer/test/fixture-projects/inconsistent-initializable/hardhat.config.js
packages/deployer/test/fixture-projects/inconsistent-initializable/package.json
packages/deployer/test/fixture-projects/sample-project/contracts/modules/InitializableModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/storage/InitializableStorage.sol
packages/deployer/test/integration/inconsistent-initializable.test.js
packages/deployer/test/unit/internal/initializable-ast-validator.test.js
packages/deployer/test/unit/utils/deployments.test.js

Add Initializable validator to Deployer

---

packages/core-contracts/contracts/mocks/utils/SetUtilMock.sol
packages/core-contracts/contracts/utils/SetUtil.sol
packages/core-contracts/test/contracts/utils/SetUtil.test.js

Implements sets in Solidity

---

packages/core-contracts/contracts/ownership/Ownable.sol
packages/core-modules/contracts/interfaces/IOwnerModule.sol
packages/core-modules/contracts/modules/OwnerModule.sol
packages/core-modules/test/helpers/initializer.js
packages/synthetix-main/contracts/interfaces/ISNXTokenModule.sol
packages/synthetix-main/contracts/interfaces/ISynthsModule.sol
packages/synthetix-main/contracts/modules/SNXTokenModule.sol
packages/synthetix-main/contracts/modules/SynthsModule.sol
packages/synthetix-main/test/contracts/modules/SNXTokenModule.test.js
packages/synthetix-main/test/contracts/modules/SynthsModule.test.js
packages/synthetix-main/test/helpers/initializer.js

Use initializableMixin where possible

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionSchedule.sol
packages/core-modules/test/contracts/modules/ElectionModule.settings.test.js

Election module/settings

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionSchedule.sol
packages/core-modules/test/contracts/modules/ElectionModule.init.test.js
packages/core-modules/test/helpers/election-helper.js
packages/deployer/tasks/deploy.js
packages/deployer/test/integration/inconsistent-initializable.test.js

Adhere to initializable pattern in ElectionModule

---

packages/core-modules/test/contracts/modules/ElectionModule.schedule.test.js
packages/deployer/internal/initializable-ast-validator.js
packages/deployer/tasks/deploy.js
packages/deployer/test/integration/inconsistent-initializable.test.js
packages/deployer/test/unit/internal/initializable-ast-validator.test.js

Fix #757 
Checking only modules and not every contract.

Fix bug on check-initializables

---

package-lock.json
packages/cli/extensions/environment.js
packages/cli/internal/signatures.js
packages/cli/subtasks/check-initializable.js
packages/cli/subtasks/execute-call.js
packages/cli/subtasks/find-contracts.js
packages/cli/subtasks/pick-contract.js
packages/cli/subtasks/pick-function.js
packages/cli/subtasks/pick-parameters.js
packages/cli/task-names.js
packages/cli/tasks/interact.js
packages/cli/test/fixture-projects/sample-project/contracts/modules/TokenModule.sol
packages/cli/test/fixture-projects/sample-project/contracts/storage/TokenStorage.sol
packages/cli/test/fixture-projects/sample-project/contracts/token/Token.sol
packages/core-js/.mocharc.json
packages/core-js/package.json
packages/core-js/test/fixtures/sample-project/contracts/Token.sol
packages/core-js/test/fixtures/sample-project/contracts/TokenModule.sol
packages/core-js/test/fixtures/sample-project/hardhat.config.js
packages/core-js/test/helpers/parse-contracts.js
packages/core-js/test/utils/ast/finders.test.js
packages/core-js/utils/ast/finders.js
packages/deployer/internal/contract-helper.js
packages/deployer/internal/initializable-ast-validator.js
packages/deployer/internal/process-contracts.js
packages/deployer/internal/storage-ast-validator.js
packages/deployer/subtasks/validate-initializables.js
packages/deployer/test/fixture-projects/sample-project/test/contracts/TokenModule.test.js
packages/deployer/test/unit/internal/initializable-ast-validator.test.js
packages/synthetix-main/contracts/modules/SynthsModule.sol

Add CLI interaction with satellites

---

packages/core-contracts/contracts/interfaces/IERC20HistoricalBalance.sol
packages/core-contracts/contracts/mocks/token/ERC20HistoricalBalanceMock.sol
packages/core-contracts/contracts/token/ERC20.sol
packages/core-contracts/contracts/token/ERC20HistoricalBalance.sol
packages/core-contracts/contracts/token/ERC20HistoricalBalanceStorage.sol
packages/core-contracts/test/contracts/token/ERC20HistoricalBalance.test.js
packages/core-js/test/utils/hardhat/rpc.test.js
packages/core-js/utils/hardhat/rpc.js

Add ERC20HistoricalBalance

---

packages/deployer/internal/storage-ast-validator.js
packages/deployer/test/fixture-projects/sample-project/contracts/modules/AnotherModule.sol

Let constants pass as safe

---

packages/core-contracts/test/contracts/initializable/Initializable.test.js
packages/core-contracts/test/contracts/proxy/BeaconProxy.test.js
packages/core-contracts/test/contracts/proxy/UUPSProxy.test.js
packages/core-contracts/test/contracts/token/ERC20.test.js
packages/core-contracts/test/contracts/token/ERC721.test.js
packages/core-contracts/test/contracts/token/ERC721Owned.test.js
packages/core-contracts/test/contracts/utils/SetUtil.test.js
packages/core-js/test/utils/assertions/assert-bignumber.test.js
packages/core-js/utils/assertions/assert-bignumber.js
packages/core-modules/test/contracts/modules/CommsMixin.test.js
packages/core-modules/test/contracts/modules/OwnerModule.test.js
packages/core-modules/test/contracts/modules/RouterCoverage.test.js
packages/deployer/test/fixture-projects/sample-project/test/contracts/SettingsModule.test.js
packages/deployer/test/fixture-projects/sample-project/test/contracts/SomeModule.test.js
packages/synthetix-main/test/contracts/modules/SNXTokenModule.test.js

Change assertBN.eq to assertBN.equal

---

packages/core-contracts/hardhat.config.js
packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/storage/ElectionStorage.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionCredentials.sol
packages/core-modules/contracts/tokens/CouncilToken.sol
packages/core-modules/hardhat.config.js
packages/core-modules/test/contracts/modules/ElectionModule.evaluate.test.js
packages/core-modules/test/contracts/modules/ElectionModule.init.test.js
packages/core-modules/test/contracts/modules/ElectionModule.nominate.test.js
packages/core-modules/test/contracts/modules/ElectionModule.resolve.test.js
packages/core-modules/test/contracts/modules/ElectionModule.schedule.test.js
packages/core-modules/test/contracts/modules/ElectionModule.settings.test.js
packages/core-modules/test/contracts/modules/ElectionModule.token.test.js
packages/core-modules/test/contracts/modules/ElectionModule.vote.test.js
packages/synthetix-main/hardhat.config.js

Election module/resolution nft

---

packages/core-js/utils/ethers/events.js
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionCredentials.sol
packages/core-modules/test/contracts/modules/ElectionModule.resolve.test.js
packages/core-modules/test/contracts/modules/ElectionModule.token.test.js

Election module/more events

---

packages/cli/test/fixture-projects/initializable/hardhat.config.js
packages/cli/test/fixture-projects/sample-project/hardhat.config.js
packages/core-contracts/contracts/proxy/UUPSImplementation.sol
packages/core-contracts/hardhat.config.js
packages/core-modules/hardhat.config.js
packages/deployer/test/fixture-projects/custom-proxy/hardhat.config.js
packages/deployer/test/fixture-projects/inconsistent-initializable/hardhat.config.js
packages/deployer/test/fixture-projects/namespace-collision/hardhat.config.js
packages/deployer/test/fixture-projects/sample-project/hardhat.config.js
packages/deployer/test/fixture-projects/sibling-contracts/hardhat.config.js
packages/synthetix-main/hardhat.config.js

Update solidity version to 0.8.11

---

packages/core-contracts/contracts/token/ERC20HistoricalBalance.sol

Election-module/erc20-rename-move-balance-function

---

packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionSchedule.sol
packages/core-modules/test/contracts/modules/ElectionModule/Initialize.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Token.test.js
packages/core-modules/test/helpers/election-helper.js

Election module/review init

---

packages/core-js/test/fixtures/variableDefNodeAst.json
packages/deployer/internal/storage-ast-validator.js
packages/deployer/test/fixture-projects/storage-collision/contracts/Proxy.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/interfaces/IAnotherModule.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/interfaces/ISomeModule.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/modules/AnotherModule.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/modules/SomeModule.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/storage/AnotherModuleStorage.sol
packages/deployer/test/fixture-projects/storage-collision/contracts/storage/SomeModuleStorage.sol
packages/deployer/test/fixture-projects/storage-collision/hardhat.config.js
packages/deployer/test/integration/storage-collision.test.js
packages/deployer/test/unit/internal/storage-ast-validator.test.js

Increase coverage to storage-ast-validator.js

---

packages/deployer/internal/storage-ast-validator.js
packages/deployer/test/fixture-projects/sample-project/contracts/interfaces/IAnotherModule.sol
packages/deployer/test/fixture-projects/sample-project/contracts/modules/AnotherModule.sol
packages/synthetix-main/contracts/token/SNXToken.sol

Allow immutable declarations

---

packages/core-contracts/contracts/errors/ArrayError.sol
packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionCredentials.sol
packages/core-modules/test/contracts/modules/ElectionModule/Dismiss.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Elect.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Evaluate.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Initialize.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Nominate.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Resolve.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Schedule.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Settings.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Token.test.js
packages/core-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Election module init council

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionVotes.sol
packages/core-modules/contracts/submodules/election/strategies/ElectionVotesBasic.sol
packages/core-modules/test/contracts/modules/ElectionModule/Dismiss.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Elect.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Evaluate.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Schedule.test.js
packages/core-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Rename elect to cast

---

packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionSchedule.sol
packages/core-modules/test/contracts/modules/ElectionModule/Dismiss.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Evaluate.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Initialize.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Schedule.test.js
packages/core-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Rename Idle period to Administration

---

packages/core-modules/contracts/submodules/election/ElectionModule.sol
packages/spartan-council/contracts/interfaces/IDebtShare.sol
packages/spartan-council/contracts/modules/ElectionModule.sol
packages/spartan-council/contracts/storage/SpartanCouncilStorage.sol

Introduce basic v2x debt shares mechanism for spartan council elections

---

packages/governance-modules/contracts/mocks/DebtShareMock.sol
packages/governance-modules/contracts/modules/ElectionModule.sol
packages/governance-modules/contracts/submodules/election/ElectionBase.sol
packages/governance-modules/contracts/submodules/election/ElectionVotes.sol
packages/governance-modules/test/contracts/modules/ElectionModule/Cast.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/DebtShare.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/Dismiss.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/Initialize.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/Settings.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Adds tests for debt shares in the ElectionModule

---

packages/core-contracts/contracts/mocks/utils/MathUtilMock.sol
packages/core-contracts/contracts/utils/MathUtil.sol
packages/core-contracts/test/contracts/utils/MathUtil.test.js
packages/core-js/test/utils/ethers/bignumber.test.js
packages/core-js/utils/ethers/bignumber.js
packages/governance-modules/contracts/mocks/DebtShareMock.sol
packages/governance-modules/contracts/submodules/election/ElectionVotes.sol
packages/governance-modules/test/contracts/modules/ElectionModule/Cast.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/DebtShare.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/Evaluate.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Introduces quadratic voting in the ElectionModule

---

packages/governance-modules/contracts/mocks/DebtShareMock.sol
packages/governance-modules/contracts/modules/ElectionModule.sol
packages/governance-modules/contracts/storage/ElectionStorage.sol
packages/governance-modules/contracts/submodules/election/ElectionVotes.sol
packages/governance-modules/test/contracts/modules/ElectionModule/CombinedDebtShare.test.js
packages/governance-modules/test/contracts/modules/ElectionModule/helpers/election-helper.js

Tests combined with L1 and L2 Debt Share + Bug fixing

---

.github/workflows/test.yml

Temporarily disable integration tests until we fix them on https://github.com/Synthetixio/synthetix-v3/issues/901

Remove integration tests temporarily

---

packages/governance-modules/cannon.json
packages/governance-modules/cannonfile.toml

Closes https://github.com/Synthetixio/gmv3-interface/issues/45

Add multiple councils on governance cannon build

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionVotes.sol
packages/core-modules/test/contracts/modules/ElectionModule/Cast.test.js
packages/synthetix-governance/.env.sample
packages/synthetix-governance/test/integration/Cast.test.js
packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/Cast.test.js

Adds withdrawVote()

---

packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/contracts/submodules/election/ElectionBase.sol
packages/core-modules/contracts/submodules/election/ElectionCredentials.sol
packages/core-modules/contracts/submodules/election/ElectionVotes.sol
packages/core-modules/test/contracts/modules/ElectionModule/Cast.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Dismiss.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Nominate.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Resolve.test.js
packages/synthetix-governance/test/integration/Cast.test.js
packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/Cast.test.js
packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/Resolve.test.js

Improves ElectionModule event emission

---

packages/synthetix-governance/contracts/submodules/election/CrossChainDebtShareManager.sol
packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/CrossChainDebtShare.test.js

Allow updating cross chain merklee tree within nomination period

---

packages/core-modules/contracts/modules/ElectionModule.sol
packages/synthetix-governance/contracts/modules/ElectionModule.sol
packages/synthetix-governance/test/integration/Cast.test.js
packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/Cast.test.js

Limiting number of candidates in votes to 1

---

packages/core-modules/contracts/interfaces/IElectionModule.sol
packages/synthetix-governance/contracts/interfaces/ISynthetixElectionModule.sol
packages/synthetix-governance/contracts/modules/ElectionModule.sol
packages/synthetix-governance/test/contracts/modules/ElectionModule/Elections.test.js

Add declareAndCast function to the ElectionModule

---

packages/core-modules/contracts/modules/ElectionModule.sol
packages/core-modules/test/contracts/modules/ElectionModule/Cast.test.js
packages/core-modules/test/contracts/modules/ElectionModule/Evaluate.test.js

Limit vote withdrawal to vote period

---

packages/synthetix-governance/contracts/submodules/election/DebtShareManager.sol
packages/synthetix-governance/test/contracts/modules/ElectionModule/Elections.test.js

Increases synthetix-governance/ElectionModule test coverage to 100%

---

.eslintrc.js
packages/synthetix-governance/.gitignore
packages/synthetix-governance/cannon.json
packages/synthetix-governance/cannonfile.toml
packages/synthetix-governance/task-names.js
packages/synthetix-governance/tasks/fixture.js
packages/synthetix-governance/tasks/set-cross-chain-debt.js

Closes https://github.com/Synthetixio/synthetix-v3/issues/947

Add merkle tree fixture for cross chain debts

---

packages/cli/extensions/environment.js
packages/cli/internal/signatures.js
packages/cli/subtasks/execute-call.js
packages/cli/subtasks/pick-function.js
packages/cli/subtasks/pick-parameters.js
packages/cli/tasks/interact.js

Adds support for overloaded fns in CLI

---

packages/synthetix-governance/README.md
packages/synthetix-governance/task-names.js
packages/synthetix-governance/tasks/fixture.js

This PR fixes the `epoch` fixture adding voting power to the hardhat accounts.

Fix fixtures voting power bug

---

packages/synthetix-main/scripts/deploy.js

Update deploy script to use new multicall ABI generator function from the Deployer.
Closes https://github.com/Synthetixio/synthetix-v3/issues/1006

Update deploy script to use multicall ABI

---

package-lock.json
packages/cli/internal/autocomplete.js
packages/cli/package.json
packages/cli/subtasks/pick-contract.js
packages/cli/subtasks/pick-function.js

Closes https://github.com/Synthetixio/project-management/issues/85

Add fuzzy search to CLI

---

packages/scripts/tasks/validate-councils.js

FYI: A tx was made to upgrade the treasury-council next epoch seat count to 4

Add seat count check to validate council script

---

packages/core-modules/contracts/modules/NftModule.sol
packages/synthetix-main/contracts/interfaces/IAccountModule.sol
packages/synthetix-main/contracts/modules/core/AccountModule.sol

- fix enumerability for accounts.
- `getAccountPermissions` that returns Array of `{ target: address, roles: Array<string> }`

Account permissions view

---

packages/common-config/hardhat.config.legacy.js
packages/common-config/hardhat.config.ts
packages/synthetix-main/scripts/deploy.js

- caching hre `getSigner` and `getSigners`

Fix deploy script

---

packages/synthetix-main/contracts/mixins/AccountRBACMixin.sol
packages/synthetix-main/test/integration/bootstrap.ts
packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.grant.test.ts

Added ``Admin`` Role. 
- admin role has all permissions

Sip 301 admin role

---

package-lock.json
packages/common-config/package.json
packages/sample-project/package.json
packages/synthetix-main/package.json
packages/synthetix-main/test/integration/modules/PoolModuleOwnership.test.ts
packages/synthetix-main/test/integration/modules/VaultRewardsModule.test.ts

This update includes error stack traces added here: https://github.com/usecannon/cannon/pull/31

Update hardhat-cannon to 1.0.27

---

.github/workflows/test.yml
package-lock.json
packages/core-utils/src/utils/assertions/assert-event.ts
packages/core-utils/src/utils/assertions/assert-revert.ts
packages/sample-project/package.json
packages/synthetix-main/test/integration/mixins/AcccountRBACMixin.permissions.ts
packages/synthetix-main/test/integration/mixins/AccountRBACMixin.test.ts
packages/synthetix-main/test/integration/modules/MarketManagerModule.test.ts
packages/synthetix-main/test/integration/modules/VaultModule.test.ts
packages/synthetix-main/test/integration/modules/core/PoolConfigurationModule/PoolConfigurationModule.test.ts

Generally minor errors, but one problem with Anvil which was reported to the tooling team.

Fix gas profile PR minor errors

---

packages/synthetix-main/contracts/modules/core/AccountModule.sol

- Fix index of account permissions.

Account Permissions iterator fix

---

packages/synthetix-main/contracts/mixins/CollateralMixin.sol
packages/synthetix-main/contracts/mixins/MarketManagerMixin.sol
packages/synthetix-main/contracts/mixins/PoolMixin.sol
packages/synthetix-main/contracts/modules/core/CollateralModule.sol
packages/synthetix-main/contracts/modules/core/LiquidationModule.sol
packages/synthetix-main/contracts/modules/core/VaultModule.sol
packages/synthetix-main/contracts/storage/CollateralStorage.sol
packages/synthetix-main/test/integration/modules/LiquidationModule.test.ts

https://gist.github.com/pleasew8t/df88a092b763531f4a8d70ef894e69e8

302 303 pre audit

---

markets/spot-market/README.md
markets/spot-market/cannonfile.toml
markets/spot-market/contracts/mixins/SynthMixin.sol
markets/spot-market/contracts/modules/SpotMarketModule.sol
markets/spot-market/hardhat.config.ts
markets/spot-market/package.json

- add `npm start` to spot market to get market up and running with one command

add npm command

---

packages/synthetix-main/contracts/interfaces/ICollateralModule.sol
packages/synthetix-main/contracts/modules/core/AccountModule.sol
packages/synthetix-main/contracts/modules/core/CollateralModule.sol
packages/synthetix-main/contracts/storage/AccountRBAC.sol
packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.grant.test.ts
packages/synthetix-main/test/integration/modules/core/CollateralModule/CollateralModule.access.test.ts
packages/synthetix-main/test/integration/storage/AcccountRBACMixin.permissions.ts

* msg.sender is the party receiving/sending tokens in deposit/withdraw
* tokens are auto-rounded to system decimals before/after deposit. there may be losses if the token has more/less decimals than the system, but these will be dusts that are ignored.
* no permission required to deposit to any account

Collateral module fixes

---

packages/synthetix-main/contracts/interfaces/IMarketCollateralModule.sol
packages/synthetix-main/contracts/modules/core/CollateralModule.sol
packages/synthetix-main/contracts/modules/core/MarketCollateralModule.sol
packages/synthetix-main/contracts/storage/CollateralConfiguration.sol

ensure market collateral works porperly with different numbers of

---

protocol/synthetix/contracts/interfaces/external/IRewardDistributor.sol
protocol/synthetix/contracts/mocks/RewardDistributorMock.sol
protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
protocol/synthetix/test/integration/modules/core/RewardsManagerModule.test.ts

- Add IERC165 to IRewardsDistributor and check on registration (like markets)
- Ensure only rewards distributor address can call distributeRewards and add test

Rewards Distributor Test Improvements

---

markets/legacy-market/cannonfile.toml
markets/legacy-market/contracts/LegacyMarket.sol
markets/legacy-market/contracts/interfaces/IV3CoreProxy.sol
markets/legacy-market/package.json
markets/legacy-market/test/integration/LegacyMarket.ts
package-lock.json
utils/common-config/package.json

just need to add the support for large-scale fork test tests

restore legacy market tests

---

utils/core-contracts/contracts/interfaces/IERC721.sol
utils/core-contracts/contracts/interfaces/IERC721Enumerable.sol
utils/core-contracts/contracts/token/ERC721.sol
utils/core-contracts/contracts/token/ERC721Enumerable.sol
utils/core-contracts/test/contracts/token/ERC721.test.ts
utils/core-contracts/test/contracts/token/ERC721Enumerable.test.ts

fixed ERC721-related audit feedbacks (see specific commits for what was fixed)

Erc721 conformity fixes

---

utils/core-contracts/contracts/interfaces/IERC20.sol
utils/core-contracts/contracts/token/ERC20.sol
utils/core-contracts/contracts/token/ERC20Permit.sol
utils/core-contracts/test/contracts/token/ERC20.test.ts

adds `increaseAllowance` and `decreaseAllowance` in accordance with Macro guidance

audit feedback: implement safe erc20 approve functions

---

markets/spot-market/contracts/utils/FeeUtil.sol
markets/spot-market/test/AtomicOrderModule.buy.test.ts

- utilization fees are average of before and after fill utilization rates.  prior to this change, we were only looking at after fill.  this PR fixes that.
- Fixes test scenarios and corresponding calculations.

Utilization Fee Changes

---

markets/spot-market/contracts/interfaces/external/IFeeCollector.sol
markets/spot-market/contracts/mocks/FeeCollectorMock.sol
markets/spot-market/contracts/modules/AsyncOrderModule.sol
markets/spot-market/contracts/modules/WrapperModule.sol
markets/spot-market/contracts/utils/FeeUtil.sol

-  add transactor to fee collector interface
- added trade type to interface

Fee Collector add transactor

---

protocol/synthetix/contracts/storage/Collateral.sol

Reconcile contradicting documentation regarding locked collateral
* Update documentation in `Collateral.sol`
N/A
Addresses Iosiro audit feedback item 5.4.3

📚 Update documentation

---

protocol/synthetix/contracts/modules/core/VaultModule.sol

Rename variable in `VaultModule.sol` to follow system-wide naming conventions 
* Rename `newCollateralAmount` to `newCollateralAmountD18`
* Fix typo
N/A
Addresses Iosiro audit feedback item 5.4.6

👷🏻‍♂️ Rename variable

---

markets/spot-market/cannonfile.toml
markets/spot-market/contracts/interfaces/IAsyncOrderConfigurationModule.sol
markets/spot-market/contracts/interfaces/IAsyncOrderModule.sol
markets/spot-market/contracts/interfaces/ISpotMarketFactoryModule.sol
markets/spot-market/contracts/modules/AsyncOrderConfigurationModule.sol
markets/spot-market/contracts/modules/AsyncOrderModule.sol
markets/spot-market/contracts/storage/AsyncOrder.sol
markets/spot-market/contracts/storage/AsyncOrderClaim.sol
markets/spot-market/contracts/storage/AsyncOrderConfiguration.sol
markets/spot-market/contracts/storage/FeeConfiguration.sol
markets/spot-market/contracts/storage/SettlementStrategy.sol
markets/spot-market/contracts/storage/SpotMarketFactory.sol
markets/spot-market/contracts/utils/FeeUtil.sol
markets/spot-market/contracts/utils/SynthUtil.sol
markets/spot-market/package.json
package-lock.json

- Cleaned up async order.
- Implemented new fee structure for async orders, remove from cancellation.
TODO:

Async order with offchain functionality

---

protocol/synthetix/storage.dump.sol
utils/core-modules/contracts/interfaces/IFeatureFlagModule.sol
utils/core-modules/contracts/modules/FeatureFlagModule.sol
utils/core-modules/test/contracts/modules/FeatureFlagModule.test.ts

Idempotent add/remove feature flag

---

protocol/synthetix/contracts/modules/core/CollateralModule.sol
protocol/synthetix/test/integration/modules/core/CollateralModule/CollateralModule.deposit.test.ts

It shuoldn't be possible to deposit to an account which hasn't been created
Feedback from OZ audit.

fix deposit in nonexistant account

---

protocol/synthetix/contracts/interfaces/IPoolConfigurationModule.sol
protocol/synthetix/contracts/modules/core/PoolConfigurationModule.sol
protocol/synthetix/contracts/storage/SystemPoolConfiguration.sol
protocol/synthetix/storage.dump.sol

update incorrect return parameter for `setPreferredPool`

---

protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
protocol/synthetix/test/integration/modules/core/RewardsManagerModule.test.ts

verify account existance before updating rewards

---

protocol/synthetix/contracts/modules/core/AssociateDebtModule.sol
protocol/synthetix/storage.dump.sol
protocol/synthetix/test/integration/modules/core/AssociateDebtModule.test.ts

just a much more clear error and reduces possibility for unexpected behavior in the future
from the oz audit

associate debt should check for account existance

---

protocol/synthetix/contracts/interfaces/IVaultModule.sol
protocol/synthetix/contracts/modules/core/VaultModule.sol
protocol/synthetix/contracts/storage/Pool.sol
protocol/synthetix/test/integration/modules/core/VaultModule.test.ts

also add tests to verify these functions in more circumstances and improve actual function names to make consistency

c-ratio functions were not consistent, fix that

---

package-lock.json
protocol/oracle-manager/package.json
protocol/oracle-manager/storage.dump.sol
protocol/synthetix/cannonfile.toml
protocol/synthetix/package.json

- released alpha 14 & 1.2.8 of oracle manager

Upgrade snx alpha 15

---

markets/legacy-market/contracts/LegacyMarket.sol
markets/legacy-market/contracts/interfaces/ILegacyMarket.sol

the auditors identified potential risks with the `LegacyMarket`. They have been addressed in this PR.

misc legacy market fixes

---

markets/perps-market/contracts/storage/PerpsAccount.sol

- Also add SNX_USD_MARKET_ID constant

Add convertAllCollateralToUsd

---

markets/perps-market/contracts/interfaces/IAccountModule.sol
markets/perps-market/contracts/modules/AccountModule.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/spot-market/contracts/interfaces/IAtomicOrderModule.sol
markets/spot-market/contracts/modules/AtomicOrderModule.sol
markets/spot-market/contracts/storage/FeeConfiguration.sol
protocol/synthetix/contracts/interfaces/IMarketCollateralModule.sol

Adds external methods `totalCollateralValue` and `totalAccountOpenInterest` to a new Account Module
Also adds view modifiers to methods that are views

Account module

---

markets/perps-market/contracts/interfaces/IPerpsMarketModule.sol
markets/perps-market/contracts/modules/PerpsMarketModule.sol
markets/perps-market/contracts/storage/PerpsMarket.sol

Adds a Market Module with external view functions needed for UI

Market module

---

markets/spot-market/README.md
markets/spot-market/cannonfile.test.toml
markets/spot-market/cannonfile.toml
markets/spot-market/contracts/interfaces/IMarketConfigurationModule.sol
markets/spot-market/contracts/modules/AsyncOrderSettlementModule.sol
markets/spot-market/contracts/modules/AtomicOrderModule.sol
markets/spot-market/contracts/modules/MarketConfigurationModule.sol
markets/spot-market/contracts/modules/SpotMarketFactoryModule.sol
markets/spot-market/contracts/modules/WrapperModule.sol
markets/spot-market/contracts/storage/MarketConfiguration.sol
markets/spot-market/storage.dump.sol
markets/spot-market/test/AsyncOrderModule.test.ts
markets/spot-market/test/AtomicOrderModule.buy.test.ts
markets/spot-market/test/AtomicOrderModule.sell.test.ts
markets/spot-market/test/AtomicOrderModule.utilization.test.ts
markets/spot-market/test/SpotMarketFactory.test.ts
markets/spot-market/test/bootstrap.ts

- added new collateral leverage parameter in market configuration.
- renamed `FeeConfiguration` to `MarketConfiguration`
- tests for `locked` and `utilization fee rate`

Collateral Leverage param

---

markets/spot-market/contracts/storage/Price.sol
markets/spot-market/contracts/storage/SettlementStrategy.sol

- used `abs` from MathUtil
- organized Price.sol

L-03: remove duplication

---

markets/spot-market/contracts/interfaces/external/IFeeCollector.sol
markets/spot-market/contracts/mocks/FeeCollectorMock.sol
markets/spot-market/contracts/modules/MarketConfigurationModule.sol
markets/spot-market/contracts/storage/MarketConfiguration.sol

- fee collector only quotes and the funds are transferred directly based on quote

H-05: Fee Collector Changes

---

markets/spot-market/contracts/interfaces/ISpotMarketFactoryModule.sol
markets/spot-market/contracts/modules/SpotMarketFactoryModule.sol
markets/spot-market/contracts/storage/SettlementStrategy.sol
markets/spot-market/storage.dump.sol
markets/spot-market/test/SpotMarketFactory.test.ts

- Check synth owner is not zero address

L-10: Input validation

---

markets/spot-market/contracts/modules/AsyncOrderSettlementModule.sol
markets/spot-market/contracts/storage/SettlementStrategy.sol
markets/spot-market/storage.dump.sol
markets/spot-market/test/AsyncOrderModule.pyth.test.ts

- remove chainlink code.  we'll come back to this PR and copy over any relevant code but until then, be gone.

L-01: remove chainlink

---

markets/spot-market/contracts/interfaces/IAsyncOrderSettlementModule.sol
markets/spot-market/contracts/modules/AsyncOrderSettlementModule.sol

- transactor is now the trader and not the keeper (msg.sender)
- N-01 also fixed in the event

L-02/N-01: fix transactor

---

protocol/oracle-manager/README.md
protocol/oracle-manager/contracts/nodes/UniswapNode.sol
protocol/oracle-manager/test/integration/nodes/UniswapNode.test.ts

used block.timestamp for the Uniswap node price timestamp

H-04 UniswapNode returns 0 as timestamp

---

markets/spot-market/contracts/interfaces/IAsyncOrderConfigurationModule.sol
markets/spot-market/contracts/interfaces/IAsyncOrderModule.sol
markets/spot-market/contracts/interfaces/IAsyncOrderSettlementModule.sol
markets/spot-market/contracts/interfaces/IAtomicOrderModule.sol
markets/spot-market/contracts/interfaces/ISpotMarketFactoryModule.sol
markets/spot-market/contracts/interfaces/IWrapperModule.sol
markets/spot-market/contracts/modules/AsyncOrderConfigurationModule.sol
markets/spot-market/contracts/modules/AsyncOrderModule.sol
markets/spot-market/contracts/modules/AsyncOrderSettlementModule.sol
markets/spot-market/contracts/modules/SpotMarketFactoryModule.sol
markets/spot-market/contracts/storage/AsyncOrder.sol
markets/spot-market/contracts/storage/AsyncOrderClaim.sol
markets/spot-market/contracts/storage/OrderFees.sol
markets/spot-market/contracts/storage/Price.sol
protocol/oracle-manager/contracts/interfaces/INodeModule.sol
protocol/oracle-manager/contracts/modules/NodeModule.sol
protocol/oracle-manager/contracts/nodes/ChainlinkNode.sol
protocol/oracle-manager/contracts/nodes/ExternalNode.sol
protocol/oracle-manager/contracts/nodes/PriceDeviationCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/PythNode.sol
protocol/oracle-manager/contracts/nodes/ReducerNode.sol
protocol/oracle-manager/contracts/nodes/StalenessCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/UniswapNode.sol
protocol/oracle-manager/contracts/storage/NodeDefinition.sol

- fix named variables in interfaces

N-13: interface consistency

---

markets/spot-market/contracts/modules/AsyncOrderModule.sol
markets/spot-market/contracts/modules/AtomicOrderModule.sol
markets/spot-market/contracts/modules/WrapperModule.sol
markets/spot-market/contracts/storage/AsyncOrderClaim.sol
markets/spot-market/contracts/storage/AsyncOrderConfiguration.sol
markets/spot-market/contracts/storage/SpotMarketFactory.sol
markets/spot-market/contracts/storage/Wrapper.sol
markets/spot-market/contracts/utils/TransactionUtil.sol
protocol/oracle-manager/contracts/interfaces/external/IExternalNode.sol
protocol/oracle-manager/contracts/mocks/MockExternalNode.sol
protocol/oracle-manager/contracts/modules/NodeModule.sol
protocol/oracle-manager/contracts/nodes/ChainlinkNode.sol
protocol/oracle-manager/contracts/nodes/ExternalNode.sol
protocol/oracle-manager/contracts/nodes/PriceDeviationCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/PythNode.sol
protocol/oracle-manager/contracts/nodes/ReducerNode.sol
protocol/oracle-manager/contracts/nodes/StalenessCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/UniswapNode.sol

- changing naming from `isValid` to `validate` for checks that revert, and vice versa

N-20: fix validator naming

---

protocol/oracle-manager/contracts/modules/NodeModule.sol
protocol/oracle-manager/test/integration/modules/NodeModule.test.ts
protocol/oracle-manager/test/integration/nodes/PriceDeviationCircuitBreakerNode.test.ts
protocol/oracle-manager/test/integration/nodes/ReducerNode.test.ts
protocol/oracle-manager/test/integration/nodes/StalenessCircuitBreakerNode.test.ts

- check if parents nodes are processable for REDUCER, PRICE_DEVIATION_CIRCUIT_BREAKER, STALENESS_CIRCUIT_BREAKER nodes

M-02 Oracle data is not validated

---

markets/spot-market/contracts/utils/TransactionUtil.sol
markets/spot-market/storage.dump.sol
markets/spot-market/test-fork/AsyncOrdersModule.e2e.test.ts
markets/spot-market/test/AsyncOrderModule.escrow.test.ts
markets/spot-market/test/AsyncOrderModule.onchain.test.ts
markets/spot-market/test/AsyncOrderModule.pyth.test.ts
markets/spot-market/test/AsyncOrderModule.test.ts

- Add `NULL` to Transaction enum which sets the value 0 to "null".

N-24: Fix Transaction Type default

---

protocol/synthetix/contracts/interfaces/IIssueUSDModule.sol
protocol/synthetix/contracts/interfaces/IMarketManagerModule.sol
protocol/synthetix/contracts/modules/core/AccountModule.sol
protocol/synthetix/contracts/modules/core/IssueUSDModule.sol
protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
protocol/synthetix/contracts/modules/core/VaultModule.sol
protocol/synthetix/contracts/storage/Pool.sol
protocol/synthetix/storage.dump.sol
protocol/synthetix/test/integration/modules/core/AccountModule/AccountModule.create.test.ts
protocol/synthetix/test/integration/modules/core/IssueUSDModule.test.ts
protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
protocol/synthetix/test/integration/modules/core/VaultModule.test.ts

SIP-318-321 fix iosiro audit feedback

---

markets/perps-market/contracts/modules/PerpsAccountModule.sol
markets/perps-market/storage.dump.sol
markets/perps-market/test/integration/Account/ModifyCollateral.test.ts
protocol/synthetix/contracts/storage/AccountRBAC.sol
protocol/synthetix/storage.dump.sol

Renamed to `PERPS_MODIFY_COLLATERAL`

Rename perps permission

---

markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
markets/perps-market/contracts/modules/MarketConfigurationModule.sol
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.commit.test.ts
markets/perps-market/test/integration/bootstrap/bootstrap.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts

- you can now set global config values or market config values directly through the `bootstrapMarkets` function

Add more params to tests

---

markets/perps-market/test/integration/bootstrap/bootstrap.ts

- automatically set all synth market collateral max's to maxUint
- automatically set synth deduction priority to the order in which the synths were created.

remove global config

---

markets/perps-market/contracts/interfaces/IAsyncOrderModule.sol
markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/modules/PerpsAccountModule.sol
markets/perps-market/contracts/storage/AsyncOrder.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsMarket.sol
markets/perps-market/contracts/storage/Position.sol
markets/perps-market/storage.dump.sol
markets/perps-market/test/integration/Market/Size.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
markets/perps-market/test/integration/Position/Funding.test.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
markets/perps-market/test/integration/bootstrap/bootstrapTraders.ts
protocol/synthetix/test/common/stakers.ts

- Funding tests as per this doc: https://docs.google.com/spreadsheets/d/1eiR9riut62MrTvUR-qlHCfSJw0lGZ9Sg0pPhqOBPEsU/edit#gid=2012716724
- Implemented realizing pnl on new order commitments.

Funding basic test and fixes

---

markets/perps-market/test/integration/Account/ModifyCollateral.withdraw.test.ts

Make sure the withdrawal tests have some non snxUSD collateral

Make sure some of our collateral tests are non usd

---

markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
markets/perps-market/contracts/modules/MarketConfigurationModule.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsMarketConfiguration.sol
markets/perps-market/hardhat.config.ts
markets/perps-market/test/integration/Account/ModifyCollateral.withdraw.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.margin.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.maxLiquidationAmount.test.ts
markets/perps-market/test/integration/Market/MarketConfigration.test.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts

This a new liquidation parameter `minimumPositionMargin`, this is a constant value in USD that can control a minimum amount of required collateral that's *NOT* based on positions size

Position min margin

---

markets/perps-market/contracts/interfaces/ILiquidationModule.sol
markets/perps-market/contracts/modules/AsyncOrderSettlementModule.sol
markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsMarket.sol
markets/perps-market/contracts/storage/PerpsMarketFactory.sol
markets/perps-market/contracts/storage/Position.sol
markets/perps-market/test/integration/Liquidation/Liquidation.margin.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.multi-collateral.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.partial.test.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
markets/perps-market/test/integration/helpers/fillPrice.ts

- write liq test with multi collateral
todo:

Liquidation tests

---

markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
markets/perps-market/contracts/mocks/FeeCollectorMock.sol
markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/modules/MarketConfigurationModule.sol
markets/perps-market/contracts/modules/PerpsAccountModule.sol
markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
markets/perps-market/contracts/storage/GlobalPerpsMarket.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsMarketFactory.sol
markets/perps-market/test/integration/Market/Market.minimumCredit.test.ts
markets/perps-market/test/integration/Market/MarketConfiguration.test.ts

- Fix minimumCredit calculation
- remove some unused imports
- remove D18 from event name and function

Fix minimumCredit (plus small fixes)

---

markets/perps-market/contracts/interfaces/ILiquidationModule.sol
markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/test/integration/Liquidation/Liquidation.margin.test.ts

- adds a new view `canLiquidate`.
- returns the liquidation reward on liquidate calls

Add liquidation view and return rewards

---

markets/perps-market/contracts/storage/AsyncOrder.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/test/integration/Market/Size.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts

Audit fixes

---

markets/perps-market/contracts/modules/AsyncOrderSettlementModule.sol

Fix accrued funding in settlement

---

README.md
protocol/governance/README.md
utils/hardhat-storage/README.md

Series of documentation fixes:
1. Fixed the links the router repo (I was trying to find this and the links were broken).
2. Fixed a typo.
3. Updated the `Package structure` as it is a bit out of date.

Fix documentation issues

---

protocol/synthetix/contracts/interfaces/IPoolModule.sol
protocol/synthetix/contracts/modules/core/PoolModule.sol
protocol/synthetix/test/integration/bootstrap.ts
protocol/synthetix/test/integration/modules/core/PoolConfigurationModule/PoolConfigurationModule.test.ts
protocol/synthetix/test/integration/modules/core/PoolModuleFundAdmin.test.ts

Part of SIP: https://sips.synthetix.io/sips/sip-342/

SIP-342 Add view function getPoolCollateralConfiguration to the PoolModule

---

utils/docgen/abis.js
utils/docgen/docgen-abis.sh

PR to docs repo generated: https://github.com/Synthetixio/Synthetix-Gitbook-v3/pull/21/files#diff-ea66a1c4db0eed093f73a2384df82b0dede52622456e15ff45d752f7d89cc8e6

Andromeda docgen

---

markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/storage/AsyncOrder.sol
markets/perps-market/test/integration/Orders/Order.marginValidation.capped.test.ts
markets/perps-market/test/integration/Orders/Order.marginValidation.test.ts

- use initial margin for currently open positions instead of maintenance

Change required margin

---

markets/perps-market/cannonfile.test.toml
markets/perps-market/contracts/modules/AsyncOrderCancelModule.sol
markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/modules/AsyncOrderSettlementEIP3668Module.sol
markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/contracts/modules/PerpsAccountModule.sol
markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
markets/perps-market/contracts/utils/Flags.sol
markets/perps-market/test/integration/Suspend.test.ts

- add new feature flag `perpsSystem` which can be used to deny access to entire system

Feature flag to suspend system

---

markets/perps-market/contracts/interfaces/IMarketEvents.sol
markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/contracts/modules/PerpsAccountModule.sol
markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
markets/perps-market/contracts/modules/PerpsMarketModule.sol
markets/perps-market/contracts/storage/AsyncOrder.sol
markets/perps-market/contracts/storage/PerpsPrice.sol
markets/perps-market/contracts/storage/Position.sol
markets/perps-market/hardhat.config.ts
markets/perps-market/test/integration/Market/MarketConfiguration.test.ts

- remove unused imports
- remove unused function
- fix a failing test
- reduce timeout (only extends failing time when the weird `ensure "done()" is called` happens)

Perps Andromeda cleanup

---

markets/perps-market/contracts/interfaces/IAsyncOrderModule.sol
markets/perps-market/contracts/modules/AsyncOrderCancelModule.sol
markets/perps-market/contracts/modules/AsyncOrderModule.sol
markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
markets/perps-market/contracts/storage/SettlementStrategy.sol
markets/perps-market/storage.dump.sol
markets/perps-market/test/integration/Market/CreateMarket.test.ts
markets/perps-market/test/integration/Market/MarketConfiguration.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.cancel.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.commit.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
markets/perps-market/test/integration/bootstrap/index.ts

Add delay in price validation to settle/cancel

---

auxiliary/OpGasPriceOracle/package.json
auxiliary/PythERC7412Wrapper/package.json
auxiliary/SpotMarketOracle/package.json
auxiliary/buyback-snx/package.json
lerna.json
markets/perps-market/package.json
markets/spot-market/package.json
protocol/oracle-manager/package.json
protocol/synthetix/package.json
utils/common-config/package.json
utils/core-contracts/package.json
utils/core-modules/package.json
utils/core-utils/package.json
utils/hardhat-storage/package.json

need to merge this to master, so lerna has the new version to upgrade from

Release 3.3.5

---

.circleci/config.yml
markets/perps-market/test/integration/Account/Margins.test.ts

- external #1951
- update simulate release job to use local IPFS

margin test - liq margin test error

---

utils/docgen/abis.js
utils/docgen/docgen-abis.sh

Plus fix ipfs url resolution for new cannon

Generate docs for Base Mainnet

---

utils/hardhat-storage/src/internal/render.ts

* Add BinaryOperation to hardhat-storage render options
* Fixing return statement on BinaryOperation render

Add BinaryOperation to hardhat-storage render options (#1992)

---

markets/perps-market/contracts/storage/AsyncOrder.sol
markets/perps-market/contracts/storage/KeeperCosts.sol
markets/perps-market/contracts/storage/PerpsMarket.sol
markets/perps-market/contracts/utils/MathUtil.sol
markets/perps-market/test/integration/Orders/Order.reduceSize.test.ts

- When trader is reducing size, ignore margin requirements as long as account is not in a liquidatable state already.
https://sips.synthetix.io/sips/sip-359/

SIP-359: Ignore margin requirements on size reduction

---

markets/bfp-market/contracts/interfaces/IMarginModule.sol
markets/bfp-market/contracts/modules/MarginModule.sol
markets/bfp-market/contracts/storage/Margin.sol
markets/bfp-market/contracts/storage/PerpMarket.sol
markets/bfp-market/contracts/storage/Position.sol
markets/bfp-market/test/integration/modules/MarginModule.test.ts

Adds `getNetAssetValueWithPrice`.

feat: add getNetAssetValueWithPrice

---

.circleci/config.yml
utils/core-utils/src/utils/hardhat/rpc.ts

Better log for TXN Receipt waiter

---

markets/perps-market/subgraph/base-mainnet-andromeda/generated/schema.ts
markets/perps-market/subgraph/base-sepolia-andromeda/generated/PerpsMarketProxy/PerpsMarketProxy.ts
markets/perps-market/subgraph/base-sepolia-andromeda/generated/schema.ts
markets/perps-market/subgraph/optimism-goerli/generated/schema.ts
markets/spot-market/subgraph/base-mainnet-andromeda/generated/schema.ts
markets/spot-market/subgraph/base-sepolia-andromeda/generated/schema.ts
markets/spot-market/subgraph/optimism-goerli/generated/schema.ts
markets/spot-market/subgraph/optimism-mainnet/generated/schema.ts
protocol/synthetix/subgraph/base-mainnet-andromeda/generated/schema.ts
protocol/synthetix/subgraph/base-sepolia-andromeda/generated/CoreProxy/CoreProxy.ts
protocol/synthetix/subgraph/base-sepolia-andromeda/generated/schema.ts
protocol/synthetix/subgraph/codegen.sh
protocol/synthetix/subgraph/mainnet/generated/schema.ts
protocol/synthetix/subgraph/optimism-mainnet/generated/schema.ts
protocol/synthetix/subgraph/subgraph.base-sepolia-andromeda.yaml

Support for base and base sepolia subgraphs.

Subgraphs for Base and Base Sepolia

---

auxiliary/RewardsDistributorExternal/cannonfile.toml
auxiliary/RewardsDistributorExternal/package.json
yarn.lock

Package name exceeded 32 chars. Fixing it

Fix package name length

---

markets/bfp-market/contracts/modules/OrderModule.sol
markets/bfp-market/contracts/storage/Position.sol
markets/bfp-market/storage.dump.sol
markets/bfp-market/test/integration/modules/MarginModule.debt.test.ts
markets/bfp-market/test/integration/modules/OrderModule.test.ts

- Also minor refactor to just turn nextMargin and collateralUsd from validateTrade

Always use oracle price for MM & IM checks and when recomputing funding/util

---

markets/bfp-market/contracts/storage/Position.sol

- Also only call getLiquidationMarginUsd once to save some gas

Make sure we calculate mm with collateralUsd

---

markets/bfp-market/contracts/modules/LiquidationModule.sol
markets/bfp-market/test/integration/modules/LiquidationModule.test.ts

Review https://github.com/Synthetixio/synthetix-v3/pull/2100 before this as #2100 also resolves failing mergeAccount tests.

Bfp market liq util

---

markets/legacy-market/cannonfile.test.toml
markets/legacy-market/cannonfile.toml

* move test cannonfile, create main cannonfile which is basically just a stripped down suitable for deployment on real network with a couple of net specific steps

prepare legacy market for mainnet release

---

.circleci/config.yml
markets/perps-market/test/integration/Liquidation/Liquidation.margin.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.multi-collateral.test.ts
markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts

Only a draft here, still plenty of work to be done
- Need to unwrap all the `it` cases because for each `it` there is a lot of preparation work being done in before/beforeAll blocks (many of them are hidden away)
- Remove all `forEach` because they are executed in parallel and not sequence
All of the `forEach` need to go!

Refactor tests: Chapter One

---

markets/bfp-market/test/generators.ts
markets/bfp-market/test/integration/modules/LiquidationModule.liquidatePostion.test.ts
markets/bfp-market/test/integration/modules/OrderModule.test.ts

- Sometimes the commitment fails with 10x leverage and some fuzzy configs

Less leverage and bigger price moves for flakey tests.

---

markets/bfp-market/contracts/interfaces/IPerpMarketFactoryModule.sol
markets/bfp-market/contracts/modules/PerpMarketFactoryModule.sol
markets/bfp-market/contracts/storage/PerpMarket.sol
markets/bfp-market/storage.dump.sol
markets/bfp-market/test/calculations.ts
markets/bfp-market/test/integration/modules/PerpMarketFactoryModule.utilisation.test.ts

Also adds a utilization digest

Utilization capped to one

---

markets/bfp-market/contracts/modules/LiquidationModule.sol
markets/bfp-market/contracts/modules/MarginModule.sol
markets/bfp-market/contracts/modules/OrderModule.sol
markets/bfp-market/contracts/modules/PerpAccountModule.sol
markets/bfp-market/contracts/storage/Margin.sol
markets/bfp-market/contracts/storage/PerpMarketConfiguration.sol
markets/bfp-market/contracts/storage/Position.sol
markets/bfp-market/test/integration/modules/MarginModule.test.ts
markets/bfp-market/test/integration/modules/OrderModule.test.ts

M-05, M-01, L-05, L-06, L-07
More to come in a separate PR.

Further Guardian BFP Market Remediation Improvements

---

markets/perps-market/cannonfile.test.toml
markets/perps-market/contracts/interfaces/IAccountEvents.sol
markets/perps-market/contracts/interfaces/IAsyncOrderSettlementPythModule.sol
markets/perps-market/contracts/interfaces/IGlobalPerpsMarketModule.sol
markets/perps-market/contracts/interfaces/ILiquidationModule.sol
markets/perps-market/contracts/modules/AsyncOrderCancelModule.sol
markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
markets/perps-market/contracts/modules/CollateralConfigurationModule.sol
markets/perps-market/contracts/modules/GlobalPerpsMarketModule.sol
markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
markets/perps-market/contracts/storage/GlobalPerpsMarket.sol
markets/perps-market/contracts/storage/GlobalPerpsMarketConfiguration.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsCollateralConfiguration.sol
markets/perps-market/contracts/storage/PerpsMarketFactory.sol
markets/perps-market/storage.dump.sol
markets/perps-market/test/integration/Account/Debt.test.ts
markets/perps-market/test/integration/Account/Margins.multiCollateral.failure.test.ts
markets/perps-market/test/integration/Account/Margins.multiCollateral.test.ts
markets/perps-market/test/integration/KeeperRewards/KeeperRewards.Settlement.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.marginOnly.test.ts
markets/perps-market/test/integration/Market/MarketDebt.withFunding.test.ts
markets/perps-market/test/integration/Markets/GlobalPerpsMarket.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.cancel.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.fees.test.ts
markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
markets/perps-market/test/integration/bootstrap/bootstrap.ts

Audit / other fixes

---

protocol/oracle-manager/contracts/nodes/StalenessCircuitBreakerNode.sol
protocol/oracle-manager/test/integration/nodes/StalenessCircuitBreakerNode.test.ts

should make it much easier to understand a stale price error when one comes up

oraclemannager: add arguments to staleness node error

---

markets/perps-market/contracts/modules/LiquidationModule.sol
markets/perps-market/contracts/storage/PerpsAccount.sol
markets/perps-market/contracts/storage/PerpsCollateralConfiguration.sol
markets/perps-market/test/integration/Account/Margins.multiCollateral.test.ts
markets/perps-market/test/integration/Liquidation/Liquidation.marginOnly.test.ts
markets/perps-market/test/integration/helpers/collateralHelper.ts

- Fix min/max collateral discount logic [Issue](https://www.notion.so/guardianaudits/C-02-af4dc12dc2164d5e8ec5f10f2372c286?pvs=4)

C-02: fix collateral discount logic

---

.circleci/config.yml
markets/bfp-market/cannonfile.test.toml
markets/bfp-market/cannonfile.toml
markets/bfp-market/contracts/interfaces/IMarketConfigurationModule.sol
markets/bfp-market/contracts/interfaces/IPerpMarketFactoryModule.sol
markets/bfp-market/contracts/modules/MarketConfigurationModule.sol
markets/bfp-market/contracts/storage/PerpMarketConfiguration.sol
markets/bfp-market/test/integration/modules/MarketConfigurationModule.test.ts

Updates the `setMarketConfigurationById` with a `recomputeFunding` call.

M-18 Add recomputeFunding in setMarketConfigurationById 

---

markets/perps-market/contracts/modules/PerpsAccountModule.sol

check if a pending order exists at payDebt

Fix H-01 (partial of previous H-04)

---

auxiliary/ArbitrumGasPriceOracle/package.json
auxiliary/BuybackSnx/package.json
auxiliary/ERC4626ToAssetsRatioOracle/package.json
auxiliary/OpGasPriceOracle/package.json
auxiliary/PythERC7412Wrapper/package.json
auxiliary/RewardsDistributor/package.json
auxiliary/RewardsDistributorExternal/package.json
auxiliary/SpotMarketOracle/package.json
auxiliary/WstEthToStEthRatioOracle/package.json
markets/bfp-market/package.json
markets/perps-market/package.json
markets/spot-market/package.json
protocol/oracle-manager/package.json
protocol/synthetix/package.json
utils/core-contracts/package.json

Notice. I didn't upgrade cannon to latest because it make lot of test to fail

Bump packages version (to release Multi-Collateral)

---

protocol/synthetix/cannonfile.toml
protocol/synthetix/test/integration/modules/core/USDTokenModule.test.ts

for example we want to be able to change the symbol of the synthetix usd token

ability to change token names from within synthetix core proxy

---

protocol/governance/contracts/interfaces/IElectionModule.sol
protocol/governance/contracts/modules/core/ElectionModule.sol
protocol/governance/package.json

There was a slight bug initializing the seat count to 1, this fix should resolve the issue for the current election. The next Election settings are fine. We will remove this function and bump the version after this election ends

Fix Epoch Seat Count

---

protocol/governance/tomls/proxy-base.toml

fo unblock snaxchain testnet omnibus deployment

added salt to initModuleBundle

---

markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
markets/perps-market/contracts/storage/PerpsPrice.sol
markets/perps-market/test/integration/Market/MarketDebt.test.ts
protocol/oracle-manager/contracts/interfaces/INodeModule.sol
protocol/oracle-manager/contracts/mocks/MockPythExternalNode.sol
protocol/oracle-manager/contracts/mocks/MockV3Aggregator.sol
protocol/oracle-manager/contracts/modules/NodeModule.sol
protocol/oracle-manager/contracts/nodes/ChainlinkNode.sol
protocol/oracle-manager/contracts/nodes/ConstantNode.sol
protocol/oracle-manager/contracts/nodes/ExternalNode.sol
protocol/oracle-manager/contracts/nodes/PriceDeviationCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/ReducerNode.sol
protocol/oracle-manager/contracts/nodes/StalenessCircuitBreakerNode.sol
protocol/oracle-manager/contracts/nodes/UniswapNode.sol
protocol/oracle-manager/contracts/nodes/pyth/PythNode.sol
protocol/oracle-manager/contracts/nodes/pyth/PythOffchainLookupNode.sol
protocol/oracle-manager/contracts/storage/NodeDefinition.sol
protocol/oracle-manager/test/integration/bootstrap.ts
protocol/oracle-manager/test/integration/modules/NodeModule.test.ts
protocol/oracle-manager/test/integration/nodes/PriceDeviationCircuitBreakerNode.test.ts
protocol/oracle-manager/test/integration/nodes/StalenessCircuitBreakerNode.test.ts
utils/core-contracts/contracts/utils/RevertUtil.sol

* initial work
* builds and initial changes applied to perps market
still some other places that could be optimized but this is a start
* update tests
need more tests for:
* what happens when the parent nodes fail
* what happens if we run the tests on the perps market
* fix warnings, add important test, and change return behavior a bit
* add test on the perps supermarket
to ensure the intended effect
* add missing upstream check
* this apparently fixes 10 tests
* audit fixes
---------
Co-authored-by: Noisekit <28145325+noisekit@users.noreply.github.com>
(cherry picked from commit a4ddc4a7247df73c8c0152238cac6f69eb2901f2)

Oracle manager process many (#2215)

---

markets/bfp-market/cannonfile.toml
markets/legacy-market/cannonfile.toml
markets/perps-market/cannonfile.toml
markets/spot-market/cannonfile.toml
protocol/governance/cannonfile.satellite.toml
protocol/governance/cannonfile.toml
protocol/oracle-manager/cannonfile.toml
protocol/synthetix/cannonfile.toml

fixes https://linear.app/ccsnx/issue/SNX-853/add-necessary-cannon-parameters-so-that-proxy-contracts-can-be

ensure that proxy artifacts can be verified

---

markets/bfp-market/contracts/storage/PerpMarket.sol
markets/bfp-market/contracts/storage/Position.sol
markets/bfp-market/contracts/utils/ErrorUtil.sol

Issue description:
https://www.notion.so/guardianaudits/M-01-1018bda5828c804ca6efd512f7564947?pvs=4

Update minimum credit validation - M01

---

auxiliary/ArbitrumGasPriceOracle/package.json
auxiliary/BuybackSnx/package.json
auxiliary/ERC4626ToAssetsRatioOracle/package.json
auxiliary/OpGasPriceOracle/package.json
auxiliary/OwnedFeeCollector/package.json
auxiliary/PythERC7412Wrapper/package.json
auxiliary/RewardsDistributor/package.json
auxiliary/RewardsDistributorExternal/package.json
auxiliary/SpotMarketOracle/package.json
auxiliary/WstEthToStEthRatioOracle/package.json
lerna.json
markets/bfp-market/package.json
markets/legacy-market/package.json
markets/perps-market/package.json
markets/spot-market/package.json
protocol/governance/package.json
protocol/oracle-manager/package.json
protocol/synthetix/package.json
utils/common-config/package.json
utils/core-contracts/package.json
utils/core-modules/package.json
utils/core-utils/package.json
utils/hardhat-storage/package.json

This reverts commit c34acf691c4d685c9caa5b6b025d7b4723c283eb.

Revert "Increment version to 3.8.1 (#2319)"

---

utils/hardhat-storage/src/subtasks/generate-testable-storage.ts
utils/hardhat-storage/src/tasks/generate-testable.ts

hh storage should be maximally decoupled from snx libraries anyway

fix build error that can happen

---

markets/treasury-market/storage.dump.json
protocol/synthetix/cannonfile.common.toml
protocol/synthetix/contracts/interfaces/IVaultModule.sol
protocol/synthetix/contracts/modules/core/VaultModule.sol
protocol/synthetix/test/integration/modules/core/VaultModule.test.ts

as part of SIP-420, it is necessary to have a function to move user's collateral and debt to a new pool without repaying debt

add delegation migrate function

---

markets/legacy-market/contracts/LegacyMarket.sol
markets/treasury-market/cannonfile.test.toml

the assigned debt value needs to be based on the actual price of snx,

fix debt value assignment calculation

---

markets/treasury-market/cannonfile.toml
markets/treasury-market/contracts/TreasuryMarket.sol
markets/treasury-market/contracts/TreasuryStakingRewards.sol

* fix remaining debug code left in the TM contract
* make the staking contract upgradable (which also means it needs to be ownable)

few final fixes
