- .gitignore
So we ignore by default:
* VS Code project folder
* OSX finder files
> Add .vscode and .DS_Store to .gitignore

- .github/workflows/lint.yml
- .solhint.json
- .solhintignore
- package-lock.json
- package.json
* Fix the `lint-sol` command to lint packages files
* Add the `node_modules` folder to the `.solhintignore` file for performance reasons
* Configure Node 16 and npm 7 on `package.json` (& github actions)
* Adds a github action for running the linter
> Updates for CI and Node versioning

- packages/deployer/subtasks/deploy-contracts.js
- packages/deployer/subtasks/deploy-modules.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/sync-sources.js
- packages/deployer/task-names.js
- packages/deployer/tasks/deploy.js
- packages/deployer/utils/contracts.js
This PR adds the subtasks necessary for deploying all the contracts on the `contracts/modules` folder.
Before deploying, searches for all the modules files at `contracts/modules/**/*.sol` and checks the following strategy:
1. If the current network is `hardhat`, it will deploy all the modules again.
2. Checks on the blockchain if the same module was deployed on another Deployment, and if weren't any changes on the bytecode, it skips the deployment of that module.
3. If the bytecode is different, it notifies the user that is going to update that specific module.
4. If the module weren't previously deployed, notifies about its creation (deployment for the first time).
> Add deploy modules subtask

- packages/deployer/subtasks/deploy-contract.js
- packages/deployer/subtasks/deploy-contracts.js
- packages/deployer/subtasks/deploy-router.js
- packages/deployer/subtasks/finalize-deployment.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/task-names.js
- packages/deployer/tasks/deploy.js
- packages/deployer/utils/contracts.js
- packages/deployer/utils/transactions.js
Add the necessary subtasks for upgrading the current proxy to point to the new Router if necessary, and finalize the deployment file.
Refactor of the `deploy-contracts.js` subtask to be divided in a single `deploy-contract` script, and a `deploy-contracts` which uses the first one.
> Add upgrade proxy & finalize deployment subtasks

- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/tasks/deploy.js
- packages/deployer/test/sample-project/test/SettingsModule.test.js
- packages/deployer/utils/deployments.js
Fix #26 
The gist of this PR is the addition of the new file:
`deployer/test/sample-project/test/SettingsModule.test.js`
This tests works on an existing deployment on local, and is run with
`npx hardhat test`
The tricky part was getting the address of the main proxy of the latest deployment. A lot of logic could have been added to the test for that, but all tests would need that logic. So, perhaps it could be a helper? But then projects using the plugin would need these helpers, and the logic probably already exists in the deployer itself. So, I tried to start exposing these "common operations" from the deployer:
https://github.com/Synthetixio/synthetix-v3/pull/50/files#diff-d27aebaf2b1cb5b872cfa531db45487b4f7376085356e4886d1024107b55d5deR16
Indeed, it does make tests really simple, but …
> Bootstraps sample-project tests

- packages/deployer/tasks/deploy.js
- packages/deployer/utils/argument-types.js
This PRs adds a custom hardhat argument type for sake of celemines on the main deploy task. This validation is necessary to make sure that we generate correct deployment files formats.
> Add custom alphanumeric type for hardhat argument

- packages/deployer/extensions/config.js
- packages/deployer/subtasks/deploy-router.js
- packages/deployer/subtasks/generate-router.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/sync-sources.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/subtasks/validate-router.js
- packages/deployer/tasks/deploy.js
- packages/deployer/test/sample-project/test/SettingsModule.test.js
- packages/deployer/utils/deployments.js
- packages/deployer/utils/relative-path.js
Closes #55
The objetive of this PR is to be more compliant with common hardhat plugin config conventions, and be able to expose more utils without being dependent on global `hre` environment.
* It moves static deployer paths definitions from `hre.deployer.paths` to `hre.config.deployer.paths`
* Removes paths that can be dynamically calculated using utils from `hre.deployer.paths.*`
* Removes all dependencies of a global `hre` on `utils/deployments.js`
> Refactor utils dependance on global environment

- packages/deployer/subtasks/sync-sources.js
- packages/deployer/utils/deployments.js
This PR removes `hre.deployer.sources` from the context, and fixes the calculation of the Router's path.
> Fix Router path resolving

- packages/deployer/subtasks/generate-router.js
Closes #94
This also fixes the __*very unlikely*__ case were the modules `BearableModule` & `BearAbleModule` would both generate the `_BEARABLEMODULE` constant and collide, instead of `_BEARABLE_MODULE` & `_BEAR_ABLE_MODULE`
> Fix modules constants names on router

- packages/deployer/extensions/environment.js
- packages/deployer/index.js
- packages/deployer/internal/autosave-object.js
- packages/deployer/internal/process-transactions.js
- packages/deployer/package-lock.json
- packages/deployer/package.json
- packages/deployer/subtasks/deploy-modules.js
- packages/deployer/subtasks/deploy-router.js
- packages/deployer/subtasks/finalize-deployment.js
- packages/deployer/subtasks/generate-router.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/print-info.js
- packages/deployer/subtasks/sync-sources.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/subtasks/validate-router.js
Fix #78
* Moves `hre.deployer.file` into `hre.deployer.data.file` so that every file the deployer writes to is 100% self contained.
* Prevents extensions to hre.deployer, so that anything that is not defined in environments.js will trhow.
* Renamed `hre.deployer.data` to `hre.deployer.deployment`.
> Clean up environment.js

- package-lock.json
- packages/core-js/utils/assertions.js
- packages/core-js/utils/logger.js
- packages/core-js/utils/rpc.js
- packages/core-js/utils/tests.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/print-info.js
- packages/deployer/tasks/deploy.js
- packages/deployer/test/sample-project/package.json
- packages/deployer/test/sample-project/test/AnotherModule.test.js
- packages/deployer/test/sample-project/test/OwnerModule.test.js
- packages/deployer/test/sample-project/test/SettingsModule.test.js
- packages/deployer/test/sample-project/test/SomeModule.test.js
- packages/deployer/test/sample-project/test/UpgradeModule.test.js
- packages/deployer/test/sample-project/test/helpers/initializer.js
- packages/deployer/utils/deployments.js
Fix #51
Usage:
`cd packages/deployer/test/sample-project`
`npx hardhat node`
`npx hardhat test`
Changes:
* Adds tests for all modules in `deployer/sample-project/test`
* Adds a few utilities to the core-js package (still not categorized into folders) that are useful in tests: rpc utils to take snapshots, reversion assertion, etc
* Adds a `--quiet` option to the deploy task so that tests can use the deploy task programmatically without dirtying output.
* Simplifies and documents `deployer/utils/deployments.js` interface.
* Adds an initializer helper to the sample-project's tests which can deploy the system, initialize it, etc.
> Tests contracts in the deployer's sample-project

- package-lock.json
- packages/core-js/utils/get-date.js
- packages/deployer/extensions/environment.js
- packages/deployer/internal/autosave-object.js
- packages/deployer/internal/contract-helper.js
- packages/deployer/internal/process-contracts.js
- packages/deployer/internal/process-transactions.js
- packages/deployer/package.json
- packages/deployer/subtasks/cancel-deployment.js
- packages/deployer/subtasks/clear-deployments.js
- packages/deployer/subtasks/deploy-contract.js
- packages/deployer/subtasks/deploy-contracts.js
- packages/deployer/subtasks/deploy-modules.js
- packages/deployer/subtasks/deploy-router.js
- packages/deployer/subtasks/finalize-deployment.js
- packages/deployer/subtasks/generate-router.js
- packages/deployer/subtasks/prepare-deployment.js
- packages/deployer/subtasks/print-info.js
- packages/deployer/subtasks/sync-sources.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/subtasks/validate-modules.js
- packages/deployer/subtasks/validate-router.js
- packages/deployer/task-names.js
- packages/deployer/tasks/deploy.js
- packages/deployer/utils/deployments.js
Closes #39
This PR adds the files `extended/${name}.sources.json` & `extended/${name}.abi.json` with the corresponding metadata for each deploy.
* It also includes some refactors on `contractData` passing and processing when deploying contracts.
* When possible, is not manually calculating the path to a contract (e.g.: `contracts/modules/SomeModule.sol`), but instead we're now taking it from the artifact data, to be more consistent with hardhat
> Add artifacts files on extended folder

- .eslintrc.js
- package-lock.json
Adds a linter rule to limit line lengths to 160 characters, and 100 characters on comments.
> Add linter rule for line length

- packages/deployer/internal/ast/ast-sources.js
- packages/deployer/internal/process-contracts.js
- packages/deployer/tasks/deploy.js
Closes #122 
This PR adds the ASTs to the `hre.deployer.deployment.sources[contractName].ast` object, which means that is also saving it to the deployments files.
---
As a follow up, I created issue #136 so we stop getting the list of Contracts from 2 different sources (manually using `glob('contracts/*')` or `hre.artifacts.get*`).
> Add contracts ast to sources deployment extended info

- packages/deployer/subtasks/clear-deployments.js
- packages/deployer/test/sample-project/contracts/mixins/OwnerMixin.sol
- packages/deployer/test/sample-project/contracts/mocks/Destroyer.sol
- packages/deployer/test/sample-project/contracts/modules/OwnerModule.sol
- packages/deployer/test/sample-project/contracts/modules/UpgradeModule.sol
- packages/deployer/test/sample-project/contracts/storage/ProxyNamespace.sol
- packages/deployer/test/sample-project/test/UpgradeModule.test.js
Fix #127
Mitigates the vulnerability where someone could destroy an uninitialized proxy implementation.
It also modifies the way that the UpgradeModule validates the "fertility" of an incoming implementation, in a way that cannot produce side effects during the check.
> Safer proxy implementation

- packages/deployer/internal/ast/router-ast-validator.js
- packages/deployer/internal/ast/storage-validator.js
- packages/deployer/subtasks/deploy-modules.js
- packages/deployer/subtasks/deploy-router.js
- packages/deployer/subtasks/generate-router.js
- packages/deployer/subtasks/sync-sources.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/subtasks/validate-router.js
Fix #148
Avoids exiting anywhere in the pipeline when it becomes evident that the system will not change. The pipeline just continues with no-ops so that the user can see deployment info, validations, etc.
Also reviews messaging so that it is more consistent.
> Do not exit pipeline, plus clean up messaging

- packages/deployer/internal/router-source-validator.js
- packages/deployer/subtasks/validate-router.js
Fix #162
This check assumes that the comment  with the module name next to a selector will be in the same line:
```
case 0x1098c085 { result := _SETTINGS_MODULE } // SettingsModule.getASettingValue()
```
However, a linter such as prettier may break the assumption:
```
case 0x1098c085 {
result := _SETTINGS_MODULE
} // SettingsModule.getASettingValue()
```
Which makes the test fail with a false negative.
Since this kind of thing is now being tested in AST checks anyway, my suggestion is that we simply remove this check, and do not dictate anything related to code formatting.
> Remove wrong modules source check in router

- .eslintrc.js
Fix #138
Note: I tried limiting to 2 params, but a lot of vanilla js functions like `filter` _can_ use 3 params, so that would imply adding a lot of disabling exception comments.
Feel free to reject this PR if you know of more sophisticated ways of doing this.
> Set eslint max-params rule

- .github/workflows/test.yml
- package-lock.json
- package.json
- packages/core-contracts/package.json
- packages/core-js/.nycrc.json
- packages/core-js/package.json
- packages/deployer/.nycrc.json
- packages/deployer/package.json
- packages/synthetix-main/hardhat.config.js
- packages/synthetix-main/package.json
Closes #202 
This PR enables the checking of `all` files on current coverage scripts, and puts the low limit error on the current coverage numbers. The idea is to bump up those numbers gradually until we reach our desired maximum.
It also removes all testing from the `syntehtix-main` package until we want to implement full fledged integration tests.
> Update coverage settings

- codecov.yml
This configuration will make codecov stop showing an error if the coverage drops less than `0.1%`, e.g.: https://github.com/Synthetixio/synthetix-v3/pull/341
> Add codecov.yml config file to be able to set coverage precision

- packages/core-contracts/contracts/proxy/BeaconProxy.sol
- packages/core-contracts/test/contracts/proxy/BeaconProxy.test.js
FIX #386 
Instead of moving `NoChange()`  error to the `CommonErrros` contract and naming it to something specific, it was cleaner to use the existing `InvalidAddress()` one, till we decide on how explicit and precise we want to be with errors.
> Remove NoChange()

- packages/deployer/subtasks/sync-proxy.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/task-names.js
- packages/deployer/tasks/deploy.js
- packages/deployer/test/fixture-projects/custom-proxy/.gitignore
- packages/deployer/test/fixture-projects/custom-proxy/Proxy.edited.sol
- packages/deployer/test/fixture-projects/custom-proxy/Proxy.original.sol
- packages/deployer/test/fixture-projects/custom-proxy/contracts/AlternativeProxy.sol
- packages/deployer/test/fixture-projects/custom-proxy/contracts/modules/UpgradeModule.sol
- packages/deployer/test/src/tasks/deploy.test.js
Closes #428
This PR fixes a bug where we were validating Storage usage on the Proxy (comparing it with the previous deployment) before compiling, which caused to throw an error because the deployer thought that it was deleted.
So, the solution implemented here breaks up the `upgrade-proxy` subtask into `sync-proxy`, and the latter is executed before running any validations, so we make sure that all the `Proxy.sol` data is loaded on the current deployments json files.
> Fix proxy storage validation

- packages/deployer/internal/storage-ast-validator.js
- packages/deployer/subtasks/validate-storage.js
- packages/deployer/test/integration/sample-project.test.js
Fix #474
Atm, if you remove a module, the storage validator will throw an error because you're not allowed to remove storage slots (or change them).
This PR allows it, but as suggested by @leomassazza, the checks are not removed; the user is warned and prompted to continue instead.
> Allow namespace removals

- packages/core-contracts/contracts/interfaces/IOwnable.sol
- packages/core-contracts/contracts/interfaces/IUUPSImplementation.sol
- packages/core-contracts/contracts/ownership/Ownable.sol
- packages/core-contracts/contracts/proxy/UUPSImplementation.sol
- packages/core-modules/contracts/interfaces/IElectionModule.sol
- packages/core-modules/contracts/modules/CoreElectionModule.sol
- packages/synthetix-main/contracts/interfaces/ISNXTokenModule.sol
- packages/synthetix-main/contracts/interfaces/ISynthsModule.sol
- packages/synthetix-main/contracts/modules/SNXTokenModule.sol
- packages/synthetix-main/contracts/modules/SynthsModule.sol
Fix #486
This PR should cover all the interfaces needed so far in the repo.
Note that not all contracts have interfaces, but only those supposed to be outward facing, i.e. that we can expect other protocols to reach into, as well as subgraphs.
> Adds interfaces for all public facing contracts

- packages/cli/subtasks/execute-call.js
- packages/core-modules/hardhat.config.js
- packages/deployer/internal/abis.js
- packages/deployer/subtasks/deploy-proxy.js
- packages/deployer/subtasks/upgrade-proxy.js
- packages/deployer/task-names.js
- packages/deployer/tasks/deploy.js
Fix #539
This PR makes the following changes associated with proxies in the deployer and cli packages:
1) Extracts some of the code in `upgrade-proxy` into a new file `deploy-proxy`.
2) Whenever a proxy is deployed, its address is stored in all contracts that will be behind this proxy, in this case all modules in a new `proxyAddress` field.
3) The CLI will now try to use this `proxyAddress` field instead of the `deployedAddress` field if found.
Note that I could have just used `.isModule` from the CLI, but I decided to go this way because the CLI may eventually target other types of proxies apart from the router proxy. With this implementation, the CLI doesn't care which type of proxy it is, it just knows that its a proxy.
> Use proxies in CLI

- .github/workflows/contract-size.yml
- package-lock.json
- packages/core-contracts/hardhat.config.js
- packages/core-contracts/package.json
- packages/core-modules/hardhat.config.js
- packages/core-modules/package.json
- packages/synthetix-main/hardhat.config.js
- packages/synthetix-main/package.json
Fix #550
The plugin [hardhat-contract-sizes](https://github.com/ItsNickBarry/hardhat-contract-sizer) was added to the packages:
* core-contracts
* core-modules
* synthetix-main
Which adds a new `npx hardhat size-contracts` hardhat task.
This PR also adds GA tests for checking if any contract is oversize in CI.
FYI, all contracts appear to be very small rn.
> Add hardhat plugin for contract sizes

- package-lock.json
- packages/core-modules/contracts/interfaces/IElectionModule.sol
- packages/core-modules/contracts/modules/CoreElectionModule.sol
- packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
- packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
- packages/core-modules/test/contracts/modules/CoreElectionModule.test.js
Fix #558 
Count Votes using Simple counting and plurality to resolve the election. 
In this way to resolve the election, the Election Evaluation is done by counting votes for candidates no matter the preference order. The candidate(s) that receives the more votes wins. 
When a vote is casted, all the candidates in the ballot receive the voting power of the voter, if the voter changes the vote (vote again with another ballot) the previous one should be rolled back (votes decremented) and new ones will receive their vote power.
At the moment of counting votes, there's a list of candidates with the votes received. We need to loop over this list to find the ones most voted and that will give us the winners of the election.
This PR also includes some cleanup.
> Add Count Votes using simple counting method

- packages/core-modules/contracts/mocks/ElectionTokenMock.sol
- packages/core-modules/contracts/modules/CoreElectionModule.sol
- packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
- packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
Fixes #579, #609 
This PR fixes the problem we had when we faced the Solidity limitation where it's not possible to add struct with nested mappings to arrays. To overcome this issue I changed the array to a mapping and added an uint index to identify the latest. As a side effect, since the uint index is used incrementally we can access (if needed) previous election data.
⚠️ This PR merges into the feature branch feature-ElectionModule and not to main. After all the small pieces of ElectionModule are done we need to merge the feature branch into main ⚠️
> Add the ability to run multiple elections

- packages/core-contracts/contracts/mocks/utils/ArrayUtilMock.sol
- packages/core-contracts/contracts/utils/ArrayUtil.sol
- packages/core-contracts/test/contracts/utils/ArrayUtil.test.js
- packages/core-modules/contracts/modules/CoreElectionModule.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
Fix #639
Note that this PR also renames the indexes array with the word "position". My idea is that we use "position" for 1-based, and "index" for 0-based.
This distinction actually found a bug in the algorithm that removes elements from the nominees array.
> Abstracts nominee removal into an ArrayUtil

- packages/core-contracts/contracts/token/ERC721.sol
- packages/core-js/utils/assertions/assert-revert.js
Even though this does not solve #273, it emits a warning whenever an error cannot be parsed, being more explicit and not just ignoring the problem.
It also addresses what I believe to be a bug in OZ ERC721 implementation.
> Tweaks on custom errors

- .github/workflows/test.yml
- packages/cli/package.json
- packages/cli/scripts/test.sh
Fix #644
This PR wraps running of CLI tests in a script. This was previously encoded in a Github Actions yaml file, which made it not evident how the tests are supposed to be ran.
Now it's encoded in npm test.
> Better way to run CLI tests

- packages/core-modules/contracts/interfaces/IElectionModule.sol
- packages/core-modules/contracts/modules/CoreElectionModule.sol
- packages/core-modules/contracts/modules/mocks/ElectionStorageMock.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
- packages/core-modules/test/contracts/modules/CoreElectionModule.Plurality.test.js
- packages/core-modules/test/contracts/modules/CoreElectionModule.test.js
Fix #666 👿  
This PR changes the name of some variables to better align with the literature. Basically a nomination is a way to be a candidate, and the vote data (what the voter present) is a ballot.
> Rename variables to align with literature

- packages/core-contracts/contracts/errors/InitError.sol
- packages/core-contracts/contracts/initializable/InitializableMixin.sol
- packages/core-contracts/contracts/mocks/initializable/InitializableMock.sol
- packages/core-contracts/test/contracts/initializable/Initializable.test.js
Fix #703  Create an initializableMixin in core-contracts and adds test coverage.
> InitializableMixin

- packages/cli/subtasks/check-initializable.js
- packages/cli/subtasks/pick-function.js
- packages/cli/task-names.js
- packages/cli/test/fixture-projects/initializable/contracts/Proxy.sol
- packages/cli/test/fixture-projects/initializable/contracts/modules/InitializableModule.sol
- packages/cli/test/fixture-projects/initializable/contracts/modules/UpgradeModule.sol
- packages/cli/test/fixture-projects/initializable/contracts/storage/InitializableStorage.sol
- packages/cli/test/fixture-projects/initializable/hardhat.config.js
- packages/cli/test/fixture-projects/initializable/package.json
- packages/cli/test/integration/check-initializable.test.js
- packages/cli/test/integration/helpers/bootstrap.js
- packages/core-js/test/utils/misc/strings.test.js
- packages/core-js/utils/misc/strings.js
- packages/deployer/internal/initializable-ast-validator.js
Fix #706
The PR adds the ability to check if the contract selected is initializable and if it is already initialized, raising a Warn message if not. That is accomplished with the introduction of a new subtask that is executed in the pick-function SUBTASK before showing the list of functions available.
> InitializableModules: Update CLI

- packages/deployer/.mocharc.json
- packages/deployer/subtasks/clear-deployments.js
This PR fixes the following error when running the sample project tests:
Which can be seen here: https://github.com/Synthetixio/synthetix-v3/runs/4880610175?check_suite_focus=true
> Fix sample-project tests

- packages/core-contracts/contracts/mocks/utils/SetUtilMock.sol
- packages/core-contracts/contracts/utils/SetUtil.sol
- packages/core-contracts/test/contracts/utils/SetUtil.test.js
Cherry pick PR for Sets implementation from https://github.com/Synthetixio/synthetix-v3/pull/696
> Implement SetUtil

- packages/core-modules/contracts/modules/ElectionModule.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
- packages/core-modules/test/contracts/modules/ElectionModule.settings.test.js
Fix #783
If `nextEpochSeatCount` is modified during the evaluation of an election, the counting algo could fail. We could limit changing this setting to _not_ be in the evaluation period only, but I figured its also better for users to have a definite seat count during nominations and vote.
> Election module/seats

- package-lock.json
- packages/cli/subtasks/find-contracts.js
- packages/core-js/test/fixtures/sample-project/contracts/AnotherModule.sol
- packages/core-js/test/fixtures/sample-project/contracts/MultipleInheritance.sol
- packages/core-js/test/fixtures/sample-project/contracts/SampleModule.sol
- packages/core-js/test/utils/ast/finders.test.js
- packages/core-js/test/utils/misc/array-filters.test.js
- packages/core-js/utils/ast/finders.js
- packages/core-js/utils/misc/array-filters.js
- packages/deployer/.nycrc.json
- packages/deployer/internal/initializable-ast-validator.js
- packages/deployer/internal/interface-ast-validator.js
- packages/deployer/internal/router-ast-validator.js
- packages/deployer/internal/satellites-validator.js
- packages/deployer/internal/storage-ast-validator.js
- packages/deployer/package.json
- packages/deployer/subtasks/validate-initializables.js
- packages/deployer/subtasks/validate-interfaces.js
- packages/deployer/subtasks/validate-router.js
- packages/deployer/subtasks/validate-satellites.js
- packages/deployer/subtasks/validate-storage.js
- packages/deployer/test/fixture-projects/inconsistent-satellites/contracts/interfaces/ITokenModule.sol
- packages/deployer/test/fixture-projects/inconsistent-satellites/contracts/modules/TokenModule.sol
- packages/deployer/test/integration/inconsistent-satellites.test.js
- packages/deployer/test/unit/internal/initializable-ast-validator.test.js
- packages/deployer/test/unit/internal/storage-ast-validator.test.js
Closes #772
The main objective of this PR is to stop relying on using `"id"`'s for querying the AST tree which started to be unreliable on edge cases and change the `finders.js` interfaces to use fully qualified names.
> Fix contracts dependencies find

- packages/core-modules/contracts/modules/ElectionModule.sol
- packages/core-modules/contracts/storage/ElectionStorage.sol
- packages/core-modules/contracts/submodules/election/ElectionBase.sol
- packages/core-modules/contracts/submodules/election/ElectionSchedule.sol
- packages/core-modules/contracts/submodules/election/ElectionTally.sol
Fix #758
This is an idea to solve the issue. Save the settings struct in a mapping:
```
struct ElectionStore {
uint a;
mapping(address => ElectionSettings) settings;
uint b;
}
```
And always call it via `store.settings[address(this)]`. In fact, always use a helper `_getElectionSettings()`that wraps this.
> Election module/storage refactor

- packages/core-modules/contracts/storage/ElectionStorage.sol
Uses a uint instead of an address key for "storage dislocation", or the pointer used to store ElectionSettings at a different location to avoid storage collisions as it grows.
> Election module/storage change

- packages/deployer/internal/storage-ast-validator.js
- packages/deployer/subtasks/validate-storage.js
- packages/deployer/test/unit/internal/storage-ast-validator.test.js
Fix #716 
This PR adds a validation for nested structs. The core of the validation is in `storage-ast-validator.js` where I add a new validator function named `findNestedStructDeclarations()`. It will check the type of the members of the storage struct to see if there is another struct inside.
> Warn about Nested structs in namespaces

- packages/synthetix-governance/contracts/interfaces/ISynthetixElectionModule.sol
- packages/synthetix-governance/contracts/modules/ElectionModule.sol
- packages/synthetix-governance/contracts/submodules/election/CrossChainDebtShareManager.sol
- packages/synthetix-governance/test/unit/contracts/modules/ElectionModule/CrossChainDebtShare.test.js
Closes #943
Closes #944
We already had a view function to see the cross chain declared debt shares of a user. I just renamed the function from `getCrossChainDebtShare(user)` to `getDeclaredCrossChainDebtShare(user)` to make it clearer.
I also added a require statement to `declareCrossChainDebtShare(user, amount, ...)` so that it reverts when a user attempts to declare twice. In the past, it just succeeded by re-writing the amount stored in the merkle tree.
> Slightly better cross chain debt share declaration

- packages/core-modules/contracts/modules/ElectionModule.sol
- packages/synthetix-governance/contracts/modules/ElectionModule.sol
- packages/synthetix-governance/test/contracts/modules/ElectionModule/Initialize.test.js
Fix #962
`synthetix-governance` adds adds a parameter to the initializer. Still, nothing stops devs from calling the wrong initializer. Even though that situation could be recoverable, this PR enforces it by blocking access to the base initializer.
> Blocking wrong initializer on EM

- packages/synthetix-governance/contracts/interfaces/IDebtShare.sol
- packages/synthetix-governance/contracts/interfaces/ISynthetixElectionModule.sol
- packages/synthetix-governance/contracts/mocks/DebtShareMock.sol
- packages/synthetix-governance/contracts/modules/ElectionModule.sol
- packages/synthetix-governance/contracts/storage/DebtShareStorage.sol
- packages/synthetix-governance/contracts/submodules/election/DebtShareManager.sol
This fix updates the expected `snapshotId` type from `uint128` to `uint`, so, it has the same interface than the one deployed on Synthetix V2: https://github.com/Synthetixio/synthetix/blob/develop/contracts/SynthetixDebtShare.sol#L98:L112
This was causing an error when trying to get the user's debt share with the `ElectionModule.getDebtShare(address)` method.
> Fix debt share snapshot id type

- package-lock.json
- packages/scripts/data/councils-epoch-0.json
- packages/scripts/data/councils-epoch-1.json
- packages/scripts/internal/import-json.js
- packages/scripts/tasks/validate-councils.js
Closes https://github.com/Synthetixio/project-management/issues/77
This PR adds:
* The ability to validate different epochs (so we can validate a future epoch)
* Validates that all council members have one `CouncilToken`
* Moves data to validate to separate json files
* This PR adds a check to confirm that all current council members own a `CouncilToken`. But, I was not able to validate that only exists the amount of `CouncilToken`'s equal to the amount of council members. This second case could by caused by a bug on the `ElectionModule.resolve()` function not burning old tokens.
> Add next epoch validation scripts

- package-lock.json
- packages/synthetix-main/cannonfile.toml
- packages/synthetix-main/package.json
- packages/synthetix-main/test/contracts/modules/FundModuleFundAdmin.test.js
- upgrade cannon
- fix call to USDToken
- fix breaking test with setting fund position
> Cannon fixes

- .github/workflows/test.yml
- packages/core-modules/test/contracts/modules/NftModule.test.js
- packages/synthetix-main/test/integration/modules/VaultModule.test.ts
- packages/synthetix-main/test/integration/modules/VaultRewardsModule.test.ts
- packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.create.test.ts
- packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.transfer.test.ts
This PR fixes some tests that were failing, and removes all file level usages of `skip` in tests.
Note that some `skip`s still exist in the tests, but they are justified with an adjacent comment. We should remove these on a different PR.
> Fix some tests and remove high level skips

- packages/core-utils/src/utils/hardhat/rpc.ts
- packages/core-utils/test/utils/hardhat/rpc.test.ts
- packages/synthetix-main/contracts/mixins/CollateralMixin.sol
- packages/synthetix-main/test/integration/modules/VaultRewardsModule.test.ts
fixes boil down to:
* using `evm_setNextBlockTimestamp` instead of just `fastForward` within
`fastForwardTo`-- ensures exact timestamp is delivered
* recognition that `evm_mine` always causse the block timestamp to
incraese by 1 second, so we should be able to account for this in the test to get
the exact time
also btw the refactoring of these tests was not exactly the same as
before, which is part of the reason why the tests were failing when they
succeeded before
> fix vault rewards module tests

- packages/synthetix-main/test/integration/bootstrap.ts
- packages/synthetix-main/test/integration/modules/VaultRewardsModule.test.ts
the rewards tests were still sometimes failing so this should ensure the timestamps are always deterministic, thereby allowing for perfect test outcomes for any time-based tests.
unfortunately anvil takes `0` seconds block timestamp interval to mean "disable" the block timestamp interval (or something) so we have to use `1` so it makes the test math a little more complicated but at least its consistent!
**note: these tests still fail with older versions of anvil**. This is because, it seems, an older version of anvil will. Please make sure you are up to date to `e947899` (or probably greater)
> fix tests again

- packages/core-contracts/contracts/mocks/utils/HeapUtilMock.sol
- packages/core-contracts/contracts/utils/HeapUtil.sol
- packages/core-contracts/test/contracts/utils/HeapUtil.test.js
- packages/synthetix-main/contracts/mixins/MarketManagerMixin.sol
- packages/synthetix-main/contracts/storage/MarketManagerStorage.sol
Moved Heap.sol from synthetix-main to core-contracts, since its generic.
Note that it was renamed to HeapUtil.sol to stay consistent with other utils in core-contracts.
> Moved Heap to core-contracts

- packages/core-modules/contracts/modules/OwnerModule.sol
- packages/synthetix-main/contracts/mocks/AggregatorV3Mock.sol
- packages/synthetix-main/contracts/mocks/IAccountRBACMixinModuleMock.sol
- packages/synthetix-main/contracts/modules/account/AccountTokenModule.sol
- packages/synthetix-main/contracts/modules/esnx/ESNXTokenModule.sol
- packages/synthetix-main/contracts/modules/mocks/AccountRBACMixinModuleMock.sol
- packages/synthetix-main/contracts/modules/snx/SNXTokenModule.sol
- packages/synthetix-main/contracts/modules/usd/USDTokenModule.sol
- packages/synthetix-main/docs/theme/helpers.ts
- packages/synthetix-main/test/integration/mixins/AccountRBACMixin.test.ts
- packages/synthetix-main/test/integration/modules/LiquidationModule.test.ts
- packages/synthetix-main/test/integration/modules/MarketManagerModule.test.ts
- packages/synthetix-main/test/integration/modules/PoolModuleFundAdmin.test.ts
- packages/synthetix-main/test/integration/modules/USDTokenModule.test.ts
- packages/synthetix-main/test/integration/modules/UtilsModule.test.ts
- packages/synthetix-main/test/integration/modules/core/CollateralModule/CollateralModule.helper.ts
- packages/synthetix-main/test/utils.ts
Removes linter warnings from v3 packages.
If we do the same with the tooling packages, we can re-enable failure on warnings on our linters.
> Fix lint warnings on non-tooling packages

- packages/synthetix-main/contracts/interfaces/ILiquidationModule.sol
- packages/synthetix-main/docs/index.md
A really minor PR that resolves a typo in `LiqudationInformation`.
> Rename Liqudation -> Liquidation

- packages/synthetix-main/contracts/mixins/AccountRBACMixin.sol
- packages/synthetix-main/contracts/modules/core/VaultModule.sol
- packages/synthetix-main/test/integration/mixins/AcccountRBACMixin.permissions.ts
- packages/synthetix-main/test/integration/modules/VaultModule.test.ts
“Assign” permission to “Delegate” permission because it allows you to delegate collateral
> rename “Assign” permission to “Delegate”

- packages/synthetix-main/contracts/mixins/AccountRBACMixin.sol
- packages/synthetix-main/contracts/modules/core/AccountModule.sol
- packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.grant.test.ts
grantPermission does not ensure the validity of granted permissions
Description
When granting a permission to a user, the caller can submit any bytes32 string as the permission parameter. This string is not validated before use, which could allow the caller to submit a malicious string that may be injected into front-end components when they access the data. Such an issue could be leveraged to perform front-end attacks such as cross-site scripting (XSS) against users accessing the malicious string through a website vulnerable to XSS.
Recommendation
The function should confirm that the submitted permission is valid before storing the data. A further improvement would be the implementation of a bitmask to handle permissions, as this would remove the use of strings and simplify the system. …
> feat: validate permission on grant

- packages/core-contracts/contracts/errors/InitError.sol
- packages/core-contracts/contracts/token/ERC721.sol
- packages/core-contracts/contracts/token/ERC721Enumerable.sol
- packages/core-contracts/contracts/token/ERC721EnumerableStorage.sol
- packages/core-contracts/test/contracts/token/ERC721.test.js
- packages/core-contracts/test/contracts/token/ERC721Enumerable.test.js
https://gist.github.com/keanumaharaj/a95315730041559abfc608a4f4becdda
Parameters not validated during initialization of ERC721 tokens
[ERC721.sol#35](https://github.com/Synthetixio/synthetix-v3/blob/4bb9679d45709827fa2e46fc11e1e88cb09f08f0/packages/core-contracts/contracts/token/ERC721.sol#L35)
Description
The ERC721 contract design uses either the token name, symbol, or baseUri to determine if it is initialized. Thus, if only one of these values were set on initialization, the others would be left unsettable. If the NFT is intended to be traded on secondary markets, then all three of these data fields may be mandatory, which would require a full redeployment of the system to correct.
Recommendation
During initialization, all of the token parameters (name, symbol, and baseUri) should be …
> validate parameters on initialization of ERC721 tokens

- packages/synthetix-main/contracts/interfaces/IAccountModule.sol
- packages/synthetix-main/contracts/modules/core/AccountModule.sol
- packages/synthetix-main/test/integration/modules/core/AccountModule/AccountModule.grant.test.ts
https://gist.github.com/keanumaharaj/a95315730041559abfc608a4f4becdda
_authorized is not accessible and testable
[AccountRBACMixin.sol#L35](https://github.com/Synthetixio/synthetix-v3/blob/4bb9679d45709827fa2e46fc11e1e88cb09f08f0/packages/synthetix-main/contracts/mixins/AccountRBACMixin.sol#L35)
Description
The _authorized internal function should be exposed using an external view function to improve composability and allow the logic to be thoroughly tested. Currently, no unit tests exist that explicitly test all possible permutations of the _authorized function's logic.
Recommendation
Introduce isAuthorized() in a manner similiar to hasPermission() to the AccountModule.sol smart contract.
> Introduce isAuthorized function

- packages/common-config/hardhat.config.ts
- packages/core-modules/contracts/interfaces/IFeatureFlagModule.sol
- packages/core-modules/contracts/modules/FeatureFlagModule.sol
- packages/core-modules/contracts/modules/mocks/SampleFeatureFlagModule.sol
- packages/core-modules/contracts/storage/FeatureFlag.sol
- packages/core-modules/test/contracts/modules/FeatureFlagModule.test.js
- packages/synthetix-main/cannonfile.toml
- packages/synthetix-main/contracts/modules/core/MarketManagerModule.sol
- packages/synthetix-main/contracts/modules/core/PoolModule.sol
- packages/synthetix-main/test/integration/bootstrap.ts
- packages/synthetix-main/test/integration/modules/core/MarketManagerModule.test.ts
- packages/synthetix-main/test/integration/modules/core/PoolConfigurationModule/PoolConfigurationModule.test.ts
- packages/synthetix-main/test/integration/modules/core/PoolModuleFundAdmin.test.ts
- packages/synthetix-main/test/integration/modules/core/PoolModuleOwnership.test.ts
- packages/synthetix-main/test/integration/modules/core/VaultModule.test.ts
- change `enabled` to `allowAll` in `FeatureFlag` storage.  This allows feature flags to be auto restricted without having to explicit set them to be restricted.
- change error from `Unauthorized` -> `FeatureUnavailable` to reduce confusion for why revert occurs.
> Change feature flag mechanism to auto restrict

- packages/synthetix-main/contracts/interfaces/ICollateralModule.sol
- packages/synthetix-main/contracts/modules/core/CollateralModule.sol
- packages/synthetix-main/contracts/storage/CollateralConfiguration.sol
- packages/synthetix-main/docs/index.md
- packages/synthetix-main/test/integration/modules/core/CollateralModule/CollateralModule.helper.ts
Better than before. Ideally the name would also signify that this doesn't impact market-provided collateral depositing.
> Rename staking enabled

- packages/synthetix-main/contracts/storage/Pool.sol
- packages/synthetix-main/contracts/storage/Vault.sol
- packages/synthetix-main/contracts/storage/VaultEpoch.sol
- packages/synthetix-main/test/integration/bootstrap.ts
- packages/synthetix-main/test/integration/storage/Pool.test.ts
add tests to verify that the system imposed max debt limit is sufficiently
protecting the protocol from debt loss.
there were some bugs identified
during this process, but they have been fixed now.
> add tests (and fix bugs) for pools

- protocol/synthetix/cannonfile.test.toml
- protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
- protocol/synthetix/contracts/storage/RewardDistribution.sol
- protocol/synthetix/contracts/storage/RewardDistributionEntry.sol
- protocol/synthetix/contracts/storage/Vault.sol
The name “DistributionEntry” suggests that this has something to do with the central “Distribution” object (like “DistributionActor”). IMO it should be renamed to break this suggested association.
> Rename DistributionEntry to RewardDistributionEntry

- protocol/synthetix/contracts/storage/Distribution.sol
- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/contracts/storage/MarketCreator.sol
- protocol/synthetix/contracts/storage/ScalableMapping.sol
Make all object/library functions internal, so that they can be accessed by generative tests.
Another alternative was to enforce encapsulation in objects by making functions that are only called from the object itself private, and rename them to start with underscore, but this would not allow us to test them directly. So we resolved to make every thing internal and that's that.
> Make all object functions internal

- .github/workflows/test.yml
- package-lock.json
- protocol/oracle-manager/cannonfile.toml
- protocol/oracle-manager/contracts/Proxy.sol
- protocol/synthetix/cannonfile.toml
- protocol/synthetix/contracts/Proxy.sol
- utils/common-config/package.json
- utils/core-contracts/contracts/proxy/UUPSProxyWithOwner.sol
- utils/hardhat-router/src/utils/tests.ts
- utils/router/package.json
- utils/router/src/utils/cannon.ts
- utils/sample-project/package.json
newly supported on cannon.
also enable running the test jobs in CI for untrusted maintainers. They don't depend on any secrets now with the latest changes.
> use create2 to get stable addresses for proxy contracts

- protocol/synthetix/contracts/modules/core/CollateralModule.sol
- protocol/synthetix/test/integration/modules/core/CollateralModule/CollateralModule.deposit.test.ts
Current collateral locks do not prevent withdrawal. This PR follows auditor's recommended fix.
* Add further validation when checking `CollateralModule.withdraw(...) `
* Test validation
I was reading through v3 today and noticed this issue mentioned by the auditor. I decided to take a few minutes to implement a fix to help out 👍
> 👷🏻‍♂️ Collateral lock withdraw fix

- protocol/synthetix/contracts/interfaces/IPoolModule.sol
Having the name indexed (or any string) makes the graph behave a weird.  I chatted to DB and he suggested to just not have the name be indexed. I think that make sense, having the id indexed should be enough.
Ps. would be nice if I get added to this repo so I don't have to fork
> PoolNameUpdated event: name should not be indexed

- utils/core-modules/contracts/interfaces/ISampleOwnedModule.sol
- utils/core-modules/contracts/modules/mocks/SampleOwnedModule.sol
- utils/core-modules/test/contracts/modules/Ether.test.ts
- utils/router/src/internal/render-router.ts
- utils/router/templates/Router.sol.mustache
As pointed out by auditors, plain ETH transfers hit the receive function and then execution gets forwarded to the routing table, where no selector match is found, thus always causing reverts in plain ETH transfers.
This PR removes the receive function from our routers and explicitly declares that they cannot receive ETH transfers.
However, this PR leaves a half finished implementation in the router to enable them eventually, which simply adds an empty receive function. Note that this receive does not forward execution to the routing table.
Finally, the body of the routing table is moved into the fallback function to save a bit of gas, since it will not be reached from other entry points with receive enabled or disabled.
> Handle plain ETH transfers

- markets/spot-market/cannonfile.test.toml
- markets/spot-market/contracts/mocks/FeeCollectorMock.sol
- markets/spot-market/contracts/utils/FeeUtil.sol
- markets/spot-market/test/AtomicOrderModule.buy.test.ts
- markets/spot-market/test/bootstrap.ts
- Adds a `FeeCalculatorMock` that collects 50% of the fees.
- Set this mock in tests and make sure the fees are collected properly and the rest are deposited into market manager.
> Fee calculator test setup/tests

- markets/spot-market/contracts/interfaces/IFeeConfigurationModule.sol
- markets/spot-market/contracts/interfaces/IWrapperModule.sol
- markets/spot-market/contracts/modules/FeeConfigurationModule.sol
- markets/spot-market/contracts/modules/WrapperModule.sol
- markets/spot-market/contracts/storage/Wrapper.sol
- markets/spot-market/contracts/utils/FeeUtil.sol
- markets/spot-market/test/WrapperModule.test.ts
- markets/spot-market/test/bootstrap.ts
- wrapper fees changed to int's as they can be negative.
- removed `wrappingEnabled` and setup a local supply cap that can be set to 0 if we need to disable.
- unwrapping is still allowed and the supply cap doesn't affect it.
- lots of tests; including negative fee tests.
> Wrapper changes / tests

- protocol/synthetix/contracts/storage/Pool.sol
- protocol/synthetix/test/integration/bootstrap.ts
- protocol/synthetix/test/integration/modules/core/IssueUSDModule.test.ts
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
- protocol/synthetix/test/integration/modules/core/VaultModule.test.ts
in audit feedback submitted by iosiro, it is possible to
it turns out this issue was related to insufficient testing of the system collateralization ratio check, which should have been deducting the balance of the system from the available credit capacity. thankfully, this was easily resolved from a solidity perspective, it was just a missing calculation in one branch.
unfortunately the fix uncovered a few other faulty tests which also had to be resolved, which is part of the reason why there are changes all over the tests for various reasons.
iosiro's provided test has been altered slightly and brought into the codebase to ensure we have strong coverage of this particular bug in the future.
cc @iosiro-security
> audit feedback: fix IssueUSDModule debt bug

- protocol/oracle-manager/cannonfile.toml
- protocol/synthetix/contracts/interfaces/IMarketManagerModule.sol
- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
- utils/common-config/hardhat.config.ts
this method should have been added in the first place. Its just a
callthrough to `Market.distributeDebtToPools` to allow for anyone to
clear out a outstanding undistributed debt through the markets
> add missing distributeDebtToPools public method

- markets/spot-market/contracts/interfaces/IFeeConfigurationModule.sol
- markets/spot-market/contracts/modules/FeeConfigurationModule.sol
- markets/spot-market/contracts/storage/FeeConfiguration.sol
- markets/spot-market/contracts/utils/FeeUtil.sol
after chatting with afif, looks like we need this back.  generally, this will be set to lower than the atomic fixed fee so users are incentivized to use async orders more.
> Async fixed fee

- protocol/synthetix/cannonfile.toml
- protocol/synthetix/contracts/interfaces/IAccountModule.sol
- protocol/synthetix/contracts/interfaces/IUtilsModule.sol
- protocol/synthetix/contracts/modules/core/AccountModule.sol
- protocol/synthetix/contracts/modules/core/CollateralModule.sol
- protocol/synthetix/contracts/modules/core/IssueUSDModule.sol
- protocol/synthetix/contracts/modules/core/LiquidationModule.sol
- protocol/synthetix/contracts/modules/core/MarketCollateralModule.sol
- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
- protocol/synthetix/contracts/modules/core/UtilsModule.sol
- protocol/synthetix/contracts/modules/core/VaultModule.sol
- protocol/synthetix/contracts/storage/Account.sol
- protocol/synthetix/contracts/storage/Config.sol
- protocol/synthetix/storage.dump.sol
- protocol/synthetix/test/integration/modules/core/AccountModule/AccountModule.create.test.ts
- protocol/synthetix/test/integration/modules/core/CollateralModule/CollateralModule.deposit.test.ts
- protocol/synthetix/test/integration/modules/core/IssueUSDModule.test.ts
- protocol/synthetix/test/integration/modules/core/LiquidationModule.test.ts
- protocol/synthetix/test/integration/modules/core/MarketCollateralModule/MarketCollateralModule.test.ts
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
- protocol/synthetix/test/integration/modules/core/PoolModuleOwnership.test.ts
- protocol/synthetix/test/integration/modules/core/RewardsManagerModule.test.ts
- protocol/synthetix/test/integration/modules/core/VaultModule.test.ts
- protocol/synthetix/test/integration/verifications.ts
- utils/core-modules/contracts/interfaces/IFeatureFlagModule.sol
- utils/core-modules/contracts/modules/FeatureFlagModule.sol
- utils/core-modules/contracts/storage/FeatureFlag.sol
- utils/core-modules/test/contracts/modules/FeatureFlagModule.test.ts
these are things we should definitely have lined up for mainnet launch. in particular:
* interaction delay timeout for the account, which prevents user from withdrawing funds from the system in the case of an accounting error which allows for them to withdraw more than they should. this should theoretically allow for us to be able to recover from basically any attack by preventing loss of funds
* add a feature to feature flags which allows for denying to all if an address is in a list. this will allow for feature similar to the "SystemStatus" system of v2x, but with more granularity and improved code maintainability
* create new feature flags which are set to allowed automatically:
* createAccount
* deposit
* withdraw
* mintUsd
* burnUsd
* liquidate
* liquidateVault
* …
> add new security features

- protocol/synthetix/contracts/interfaces/IVaultModule.sol
- protocol/synthetix/contracts/modules/core/VaultModule.sol
- protocol/synthetix/storage.dump.sol
- protocol/synthetix/test/integration/modules/core/PoolModuleFundAdmin.test.ts
- protocol/synthetix/test/integration/modules/core/VaultModule.test.ts
`VaultModule.delegateCollateral()` can be called with a `newCollateralAmount` equal to the `currentCollateralAmount`. This can lead to unexpected behavior. Add a check to prevent this edge case.
* Add comparison check
* Add customer error
* Test new logic
N/A
Addresses Iosiro audit feedback item 5.3.3
> 🔎 Update VaultModule logic

- protocol/synthetix/contracts/interfaces/IAssociateDebtModule.sol
If an account is not part of a distribution, the amount of debt assigned to the account would increase as expected. However, if an account is already part of a distribution, and has some existing debt shares in the vault, their debt will first be decreased pro-rata before being increased by the associated debt amount. This functionality may seem confusing, but its actually correct outcome when considering the use case.
this was raised as part of the OZ audit.
> add additional documention to clarify `associateDebt`

- protocol/synthetix/contracts/interfaces/ICollateralModule.sol
- protocol/synthetix/contracts/modules/core/CollateralModule.sol
- protocol/synthetix/contracts/storage/CollateralLock.sol
- protocol/synthetix/storage.dump.sol
- protocol/synthetix/test/integration/modules/core/CollateralModule/CollateralModule.locks.test.ts
fixes a number of issues identified during the audit related to collateral locks:
* `cleanExpiredLocks` was not correctly limiting its iteration
* `createLock` was not validating inputs enough (ex. creating lock in the past)
* lack of emitted events
found as part of the OZ audit
> fixes for collateral locks

- protocol/synthetix/contracts/modules/core/AssociateDebtModule.sol
- protocol/synthetix/contracts/storage/Pool.sol
- protocol/synthetix/contracts/storage/Vault.sol
- protocol/synthetix/storage.dump.sol
collateralAmounts ScalableMapping is manually calculated, when such a
function is already implemented.
could be removed in favor of using the one defined in the Account storage library.
manually instead of calling the dedicated currentAccountCollateral function.
the currentVaultDebt function.
> N13: remove duplicate code

- protocol/synthetix/contracts/interfaces/IRewardsManagerModule.sol
- protocol/synthetix/contracts/interfaces/external/IRewardDistributor.sol
- protocol/synthetix/contracts/mocks/RewardDistributorMock.sol
- protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
- protocol/synthetix/test/integration/modules/core/RewardsManagerModule.test.ts
if a reward distributor returns false, it means something went wrong with the payout, but the distributor doesn't want to revert itself for some reason. ensure that this case is properly handled.
part of oz audit
> handle `false` response from reward distributor `payout`

- protocol/synthetix/contracts/modules/core/AccountModule.sol
- protocol/synthetix/contracts/storage/AccountRBAC.sol
- protocol/synthetix/test/integration/modules/core/AccountModule/AccountModule.transfer.test.ts
All permissions granted by the previous owner should be cleared on account transfer
identified in oz audit
> fix account permissions not fully cleared on transfer

- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/test/integration/modules/core/MarketCollateralModule/MarketCollateralModule.test.ts
when there is market deposited collateral, it should be possible for creditCapacity to go negative in order to protect against overruns when more collateral is withdrawn from the market than capacity provided by the pools.
when there is no deposited collateral, then creditcapacity functions same as before.
found as part of oz audit
> fix credit capacity handling with market deposited collateral

- markets/legacy-market/contracts/LegacyMarket.sol
- protocol/synthetix/contracts/modules/core/CollateralModule.sol
- protocol/synthetix/contracts/modules/core/LiquidationModule.sol
- protocol/synthetix/contracts/modules/core/MarketCollateralModule.sol
- protocol/synthetix/contracts/storage/Distribution.sol
- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/contracts/storage/RewardDistribution.sol
- protocol/synthetix/contracts/storage/ScalableMapping.sol
tokenAmount into systemAmount (18 decimals). This performs an external call to
check the token decimals which can be avoided if authorized access is checked first.
be negative at this point because isLiquidatable would have returned false and reverted
earlier. It can be safely casted to uint without checking whether it is a non-negative
value.
totalSharesD18 but then is not using it in line 89.
through all DepositedCollateral entries and queries the current USD price through
the Oracle. Consider first checking whether the amount of collateral is larger than zero, in
order to avoid querying the Oracle in that case.
with the goal of updating a specific actor's last value per share and recovering the value
change since the last interaction. In order to update this value in storage, the …
> N-15: gas optimizations

- .github/workflows/check-packages.yml
- .github/workflows/test.yml
- markets/spot-market/storage.dump.sol
- package.json
- utils/hardhat-storage/README.md
- utils/hardhat-storage/src/tasks/verify.ts
- utils/sample-project/contracts/storage/GlobalStorage.sol
This PR fixes the following:
1. Adds all the contracts from `contracts/` folders to the storage check, not only the ones in `contracts/modules/**`
2. Adds a github action to check that the developer has updated the storage dump file (meaning that it was checked)
3. Updates the old ci package-lock check to not use an unnecessary github action dependency
> (M-4) Add storage slot validation on all contracts

- utils/core-contracts/test/contracts/proxy/UUPSProxy.test.ts
- utils/router/src/internal/render-router.ts
- utils/router/test/src/generate.test.ts
This PR takes care of the following:
1. Re-add selectors duplication validations when generating the Router's, which was removed temporarily during this migration: https://github.com/Synthetixio/synthetix-v3/pull/1435
2. Makes sure that the Proxies implementations do not have public facing methods, so they cannot unknowingly block the execution from the implementation.
> (M-1) Fix selectors validations

- markets/spot-market/contracts/utils/SynthUtil.sol
- utils/core-modules/contracts/interfaces/IDecayTokenModule.sol
- utils/core-modules/contracts/modules/DecayTokenModule.sol
- utils/core-modules/contracts/modules/TokenModule.sol
fixes open zeppelin audit feedback regarding types in the `ISpotMarketFactory` being contrary to their actual purpose. additionally, `IDecayTokenModule` did not inherit from `TokenModule` even though they share nearly the same interface. so this was corrected, as well as changing `SynthUtil` to return `ISynthTokenModule`
> L-05 fix decay token inheritance

- protocol/oracle-manager/contracts/nodes/UniswapNode.sol
- protocol/oracle-manager/test/integration/nodes/UniswapNode.test.ts
- If secondsAgo is equal to 0 the oracle would revert at any process call. This change would make sure no uniswap node with secondsAgo == 0 can be created.
> M-03 Missing validation in Uniswap Oracle's configuration

- markets/spot-market/contracts/modules/WrapperModule.sol
- markets/spot-market/contracts/storage/AsyncOrder.sol
- for wrappers and escrowing synths, use `safeTransfer` and `safeTransferFrom`.
for other tokens (such as USD token) and when transferring into the spot market system, using the normal `transfer` function to save gas.
> L-17: safe transfers

- markets/spot-market/contracts/interfaces/ISpotMarketFactoryModule.sol
- markets/spot-market/contracts/modules/SpotMarketFactoryModule.sol
- markets/spot-market/test/SpotMarketFactory.test.ts
- markets/spot-market/test/bootstrap.ts
add a function to `setDecayRate` on `SpotMarketFactory`
additionally, it was identified that if we do this, we need to keep a leash on what the supported types of collateral token implementations are. so, this PR also limits the `upgradeSynthImpl` function to only upgrading to the *current* synth implementation
also, there wer emissing tests for `upgradeSynthImpl`, so those have been added.
> M-01 fix cannot set decay rate

- markets/spot-market/cannonfile.toml
* as is standard now, all `invoke` steps should use camel case
* not necessary to have `coryProxyOwner` setting
* can now inject `formatBytes32String` directly into the command rather than just precalculating it and adding a comment
> cleanups for spot market cannonfile

- markets/spot-market/README.md
- markets/spot-market/contracts/modules/MarketConfigurationModule.sol
- markets/spot-market/contracts/modules/WrapperModule.sol
- markets/spot-market/contracts/storage/MarketConfiguration.sol
- markets/spot-market/contracts/storage/Wrapper.sol
- markets/spot-market/storage.dump.sol
- markets/spot-market/test/WrapperModule.test.ts
> Audit fixes

- protocol/synthetix/contracts/interfaces/ICrossChainPoolModule.sol
- protocol/synthetix/contracts/interfaces/IUSDTokenModule.sol
- protocol/synthetix/contracts/interfaces/IUtilsModule.sol
- protocol/synthetix/contracts/modules/core/CrossChainPoolModule.sol
- protocol/synthetix/contracts/modules/core/UtilsModule.sol
- protocol/synthetix/contracts/modules/usd/USDTokenModule.sol
- protocol/synthetix/contracts/storage/Pool.sol
- protocol/synthetix/storage.dump.sol
- protocol/synthetix/test/common/stakedPool.ts
- protocol/synthetix/test/integration/bootstrap.ts
- protocol/synthetix/test/integration/modules/core/CcipReceiverModule.test.ts
- protocol/synthetix/test/integration/modules/core/CrossChainPoolModule.test.ts
- protocol/synthetix/test/integration/modules/core/USDTokenModule.test.ts
- protocol/synthetix/test/integration/modules/core/VaultModule.test.ts
This was requested by CCIP for testing purposes with their token pools.
> Implement burn from sender

- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/GlobalPerpsMarketConfiguration.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/contracts/storage/PerpsMarketConfiguration.sol
- markets/perps-market/storage.dump.sol
- added `liquidationRewardRatioD18`
- calculated liquidationReward based on the above ratio * notional value.  
- checked against global min/max liquidation reward values.
- applied to maintenance margin to determine liquidations and withdrawal of margin.
- refactored `liquidate` on account to take into account liquidation rewards and pay them out properly.
> Liquidation rewards perps v3

- markets/perps-market/contracts/modules/AsyncOrderModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/SettlementStrategy.sol
- markets/perps-market/storage.dump.sol
- markets/perps-market/test/integration/Market/CreateMarket.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.commit.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.price.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrap.ts
- markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
- markets/perps-market/test/integration/helpers/openPosition.ts
- utils/core-utils/src/utils/hardhat/rpc.ts
- Remove legacy ONCHAIN strategy from AsyncOrder
- Fix missing check of `acceptablePrice`
- Add tests for covering `acceptablePrice` and `priceDeviation`
- Add missing test on pyth data
> Add tests for price deviations

- markets/perps-market/contracts/modules/AsyncOrderModule.sol
- markets/perps-market/contracts/modules/AsyncOrderSettlementModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/contracts/storage/PerpsMarket.sol
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
move location of AsyncOrder from markets as mapping to single instance on Account since we are only supporting one pending order per account.
> Change location of async order

- markets/perps-market/contracts/modules/AsyncOrderModule.sol
- markets/perps-market/contracts/modules/AsyncOrderSettlementModule.sol
- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
This PR updates the location of the AsyncOrder instead of adding it to the Account Data struct, it gets loaded from the AsyncOrder library
> Use load instead of mapping for AsyncOrder

- markets/perps-market/contracts/interfaces/IAsyncOrderModule.sol
- markets/perps-market/contracts/interfaces/IPerpsAccountModule.sol
- markets/perps-market/contracts/interfaces/IPerpsMarketModule.sol
- markets/perps-market/contracts/modules/AsyncOrderModule.sol
- markets/perps-market/contracts/modules/LiquidationModule.sol
- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- markets/perps-market/contracts/modules/PerpsMarketModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/contracts/storage/PerpsMarketConfiguration.sol
- markets/perps-market/test/integration/Account/Margins.test.ts
- markets/perps-market/test/integration/Account/ModifyCollateral.withdraw.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.fees.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrap.ts
- markets/perps-market/test/integration/helpers/computeFees.ts
- markets/perps-market/test/integration/helpers/index.ts
- Adds three new views: `computeOrderFees`, `getWithdrawableMargin`, `getRequiredMargins`.
- Uses initial margin instead of maintenance margin for withdrawable margin calc.
- Tests (and a small `computeFees` types change)
> add new views

- markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
- markets/perps-market/contracts/modules/MarketConfigurationModule.sol
- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/contracts/storage/PerpsMarketConfiguration.sol
- markets/perps-market/test/integration/Account/Margins.test.ts
- markets/perps-market/test/integration/Account/ModifyCollateral.withdraw.test.ts
- markets/perps-market/test/integration/Liquidation/Liquidation.margin.test.ts
- markets/perps-market/test/integration/Liquidation/Liquidation.maxLiquidationAmount.test.ts
- markets/perps-market/test/integration/Liquidation/Liquidation.multi-collateral.test.ts
- markets/perps-market/test/integration/Market/MarketConfiguration.test.ts
- markets/perps-market/test/integration/Market/MarketDebt.withFunding.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
- removed `maintenanceMarginRatio`
- added `minimumInitialRatio` -> this ratio is added to the computed initial ratio based on the configured `initialMarginRatio`
- added `maintenaceMarginScalar` -> this scalar is multiplied by initial margin ratio to get the maintenance margin ratio
> New liquidation params

- markets/perps-market/contracts/modules/LiquidationModule.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/test/integration/Liquidation/Liquidation.maxLiquidationAmount.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrap.ts
- when the amountToLiquidate is 0, abort from doing the rest of the liquidation stuff; saves gas too
> Optimize 0 position liquidation

- markets/perps-market/cannonfile.toml
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/storage.dump.sol
- rename `AccountProxy` -> `PerpsAccountProxy`.
- fix `AcceptablePrice` params
> Small fixes

- .github/workflows/test.yml
- markets/perps-market/contracts/modules/AsyncOrderModule.sol
using `actions/cache` action, cache cannon package data and hardhat artifacts cache.
reduces build time of tests by about 3 minutes.
> cache cannon builds, remove ipfs dependency

- .circleci/config.yml
We bootstrap per test file and not per test because we use `before` and not `beforeEach`, so this might not help.
If it won't - will change bootstrapping to use `beforeEach` instead and avoid state sharing between tests
> Retry failed tests 3 times

- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/test/integration/Account/ModifyCollateral.withdraw.test.ts
Issue: if an account wants to withdraw collateral that is available in the system but not on the account it reverts with overflow. 
Fix: Add an explicit revert
Hidden issue: when withdrawing collateral, use the snxUSD value to check against limits, not the nominal value
> Withdraw different collateral fix

- markets/perps-market/contracts/interfaces/ILiquidationModule.sol
- markets/perps-market/contracts/modules/LiquidationModule.sol
- markets/perps-market/contracts/modules/MarketConfigurationModule.sol
- markets/perps-market/contracts/storage/Liquidation.sol
- markets/perps-market/contracts/storage/PerpsMarket.sol
- Continue pushing to `Liquidation.Data[]` and check the previous timestamps for the liquidation amount in the current liquidation window.
> Refactor max liquidation amount to use one array

- markets/perps-market/cannonfile.test.toml
- markets/perps-market/cannonfile.toml
- markets/perps-market/contracts/interfaces/IGlobalPerpsMarketModule.sol
- markets/perps-market/contracts/interfaces/ILiquidationModule.sol
- markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
- markets/perps-market/contracts/interfaces/IPerpsMarketFactoryModule.sol
- markets/perps-market/contracts/modules/GlobalPerpsMarketModule.sol
- markets/perps-market/contracts/modules/LiquidationModule.sol
- markets/perps-market/contracts/modules/MarketConfigurationModule.sol
- markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/contracts/storage/PerpsMarketFactory.sol
- markets/perps-market/storage.dump.sol
- markets/perps-market/test/integration/Market/CreateMarket.test.ts
- markets/perps-market/test/integration/Markets/GlobalPerpsMarket.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.referrer.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
> More Audit fixes

- protocol/synthetix/contracts/interfaces/IMarketCollateralModule.sol
- protocol/synthetix/contracts/interfaces/IMarketManagerModule.sol
- protocol/synthetix/contracts/modules/core/MarketCollateralModule.sol
- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/test/integration/modules/core/MarketCollateralModule/MarketCollateralModule.test.ts
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
- protocol/synthetix/test/integration/verifications.ts
As a follow up to https://github.com/Synthetixio/synthetix-v3/pull/1849
SIP: https://sips.synthetix.io/sips/sip-343/
> SIP-343 Add extra fields to existing Market Events to track market debt changes

- .circleci/config.yml
To avoid any potential cross-build caching issues related to contracts, cannon, tests, etc we are now going to cache build artifacts only for current build number. We still have benefits when running parallel test as there is no need to compile/build testable code, as we only do it once. But we will now do it for every new build, so no cross-commit cache contamination
> Cache only for the current build

- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/test/integration/Liquidation/Liquidation.maxLiquidationAmount.macro.test.ts
- markets/perps-market/test/integration/Market/MarketDebt.withFunding.test.ts
- markets/perps-market/test/integration/Orders/OffchainAsyncOrder.settle.test.ts
- markets/perps-market/test/integration/Orders/Order.marginValidation.capped.test.ts
- markets/perps-market/test/integration/Orders/Order.marginValidation.test.ts
- markets/perps-market/test/integration/Orders/Order.marginWithPd.test.ts
- markets/perps-market/test/integration/Suspend.test.ts
- markets/perps-market/test/integration/helpers/requiredMargins.ts
When validating an order, the current logic is:
```
currentAvailableMargin > requiredMargin
```
but the new logic will reduce `currentAvailableMargin` by the immediate pnl that the fill price would create due to skew:
```
currentAvailableMargin += immediatePnlFromOrder
currentAvailableMargin > requiredMargin
```
Note: the pnl is only applied if it's negative, when it's positive, it's ignored and does not _add_ to your currentAvailableMargin
> Price impact on available margin on order validation

- .circleci/config.yml
- README.md
- lerna.json
Deprecate `release` branch and publish releases to `main` branch directly
> Release from `main` branch only

- markets/perps-market/contracts/interfaces/IPerpsMarketFactoryModule.sol
- markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
- markets/perps-market/contracts/storage/PerpsMarketFactory.sol
- markets/perps-market/storage.dump.sol
- markets/perps-market/test/integration/Markets/GlobalPerpsMarket.test.ts
- markets/perps-market/test/integration/bootstrap/bootstrapPerpsMarkets.ts
- will be using the setter for setting market name instead of as part of `initializeFactory`.  cannon caches the `initializeFactory` call so it wouldn't get called again and the function call in cannon was not updated to include name.
> remove name from initialize

- auxiliary/OpGasPriceOracle/contracts/OpGasPriceOracle.sol
> Add a flag to use ecotone or legacy

- markets/perps-market/contracts/interfaces/ILiquidationModule.sol
- markets/perps-market/contracts/modules/LiquidationModule.sol
- markets/perps-market/test/integration/Orders/LargSizePosition.test.ts
- protocol/synthetix/contracts/interfaces/IMarketManagerModule.sol
- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
> SIP-361 Changes Part 2

- markets/perps-market/contracts/interfaces/IMarketConfigurationModule.sol
- markets/perps-market/contracts/modules/MarketConfigurationModule.sol
- markets/perps-market/contracts/storage/GlobalPerpsMarket.sol
- markets/perps-market/test/integration/Market/MarketConfiguration.test.ts
- markets/perps-market/test/integration/Position/InterestRate.test.ts
This PR rolls back the change on getMaxMarketSize to return only one value and adds a new getMaxMarketValue to obtain the other parameter.
It also fixes an issue with `utilizationRate()` where the 2nd returned a value was always zero due to missing initialization of the value itself.
> Rollback breaking change + minor issue fix

- .circleci/config.yml
- auxiliary/ArbitrumGasPriceOracle/.gitignore
- auxiliary/ArbitrumGasPriceOracle/LICENSE
- auxiliary/ArbitrumGasPriceOracle/README.md
- auxiliary/ArbitrumGasPriceOracle/cannonfile.test.toml
- auxiliary/ArbitrumGasPriceOracle/cannonfile.toml
- auxiliary/ArbitrumGasPriceOracle/contracts/ArbGasPriceOracle.sol
- auxiliary/ArbitrumGasPriceOracle/contracts/interfaces/ArbGasInfo.sol
- auxiliary/ArbitrumGasPriceOracle/hardhat.config.ts
- auxiliary/ArbitrumGasPriceOracle/package.json
- auxiliary/ArbitrumGasPriceOracle/storage.dump.sol
- auxiliary/ArbitrumGasPriceOracle/tsconfig.json
- yarn.lock
Arbitrum deployment support
> does not include cannon deployment updates (incl. configuration, etc)
* Create `IExternalNode` inheriting contract `ArbGasPriceOracle` to process and price gas
* Fetch L2 gas price via `ArbGasInfo.getPricesInWei` (see Go implementation [here](https://github.com/OffchainLabs/nitro/blob/a20a1c70cc11ac52c7cfe6a20f00c880c2009a8f/precompiles/ArbGasInfo.go#L56))
* Fetch L1 gas price via `ArbGasInfo.getL1BaseFeeEstimate` (see Go implementation [here](https://github.com/OffchainLabs/nitro/blob/22e80a4544b0e402ce58695c3d7f6048b06e16b0/arbos/l1pricing/l1pricing.go#L217))
* Omitted `overhead` and `scalar` from `ArbGasPriceOracle .getCostOfExecutionEth` due to Arbitrum nitro mechanism (see [fee pool](https://research.arbitrum.io/t/l1-calldata-data-pricing-sequencer-reimbu …
> 🔮 Arbitrum Gas Price Oracle

- markets/bfp-market/contracts/modules/FeatureFlagModule.sol
- markets/bfp-market/contracts/modules/LiquidationModule.sol
- markets/bfp-market/contracts/modules/MarginModule.sol
- markets/bfp-market/contracts/modules/MarketConfigurationModule.sol
- markets/bfp-market/contracts/modules/OrderModule.sol
- markets/bfp-market/contracts/modules/SettlementHookModule.sol
- markets/bfp-market/contracts/storage/Position.sol
Use ERC2771Context_msgSender() instead of msg sender.
Except PerpRewardDistributor and mocks
> msg.sender -> ERC2771Context._msgSender()

- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- this function was potentially required for the storage issue, but is no longer needed.  removal prior to next deploy
> Remove previous fix function

- .circleci/config.yml
- package.json
Now we have ability to rerun only failed tests, skipping all the successful ones.
There is also an optimisation that skips the full yarn install and few more steps if there is no tests in the job, so we have an early successful exit.
> Rerun failed tests only

- markets/bfp-market/test/integration/modules/OrderModule.test.ts
- Liquidate margin only trade test to show that account that can have its margin liquidated cant open positions.
- Require the fromAccount to have a position when splitting.
> Liquidate margin only trade test

- protocol/synthetix/contracts/interfaces/IRewardsManagerModule.sol
- protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
- protocol/synthetix/test/integration/modules/core/RewardsManagerModule.test.ts
adds a new method to rewards manager module, `distributeRewardsByOwner`, which allows for an owner of the pool to change the rewards distribution setting outside of RD operation.
notes:
* it was previously intended that RD should always drive the distribution settings on the core system. however, there doesn't seem to be any downsides in allowing pool owner to have control over the distribution as well, and can provide a helpful lever in recovering from errorneous situations such as these
* renamed the function instead of overdubbing the same method to prevent confusion in function, since there are a lot of params for both and they look similar.
* tests added
> update reward distributor to support owner override

- markets/bfp-market/cannonfile.test.toml
- markets/bfp-market/cannonfile.toml
- markets/bfp-market/contracts/interfaces/IPerpMarketFactoryModule.sol
- markets/bfp-market/contracts/modules/LiquidationModule.sol
- markets/bfp-market/contracts/modules/MarginModule.sol
- markets/bfp-market/contracts/modules/OrderModule.sol
- markets/bfp-market/contracts/modules/PerpAccountModule.sol
- markets/bfp-market/contracts/modules/PerpMarketFactoryModule.sol
- markets/bfp-market/contracts/modules/PerpRewardDistributorModule/PerpRewardDistributorFactoryModule.sol
- markets/bfp-market/contracts/storage/Margin.sol
- markets/bfp-market/contracts/storage/Order.sol
- markets/bfp-market/contracts/storage/PerpMarket.sol
- markets/bfp-market/contracts/storage/PerpMarketConfiguration.sol
- markets/bfp-market/contracts/storage/Position.sol
- markets/bfp-market/storage.dump.sol
- markets/bfp-market/test/integration/modules/LiquidationModule.partialLiquidation.test.ts
- markets/bfp-market/test/integration/modules/PerpMarketFactoryModule.test.ts
This branch is based on remove spot market. Given the amount of change this is what the saving looks like.
Each method was called 200 times:
| Method           | main    | remove-spot-market | gas-optimisation |
|------------------|---------|--------------------|------------------|
| modifyCollateral | 403,580 | 366,752            | 360,254          |
| withdrawAll      | 440,326 | 374,100            | 368,110          |
| settleOrder      | 747,879 | 733,693            | 730,653          |
| commitOrder      | 330,954 | 324,794            | 322,354          |
| liquidatePosition| 350,435 | 351,239            | 345,828          |
| flagPosition     | 534,559 | 488,016            | 463,553          |
| payDebt          | 162,289 | 162,315            | 159,936          |
> Gas optimisations

- markets/bfp-market/cannonfile.toml
- markets/bfp-market/contracts/interfaces/IMarketConfigurationModule.sol
- markets/bfp-market/contracts/modules/MarketConfigurationModule.sol
- markets/bfp-market/storage.dump.sol
- markets/bfp-market/test/bootstrap.ts
- markets/bfp-market/test/helpers.ts
- markets/bfp-market/test/integration/modules/MarketConfigurationModule.test.ts
Some minor changes discovered while working on testnet deployemnet.
-  Make `marketId` part of `ConfigureByMarketParameters`, this makes the cannon file in synthetix-deployments behave a bit nicer. 
-  Include `setRewardDistributorImplementation` in the production cannonfile. We already have it in the cannon test file, and I think it make sense to have it here rather than in synthetix-deployment as it should behave differently on different networks
> Testnet deployment fixes

- utils/core-contracts/contracts/interfaces/IConfigurable.sol
- utils/core-contracts/contracts/mocks/utils/ConfigurableMock.sol
- utils/core-contracts/contracts/ownership/Configurable.sol
- utils/core-contracts/contracts/ownership/ConfigurableStorage.sol
- utils/core-contracts/package.json
- utils/core-contracts/test/contracts/ownership/Configurable.test.ts
* saving work so far
* contracts draft finished
* added set configurer and changed fn name
* changed to configurable, context msg sender, and seperated contracts
* removed setConfigurer from ownable
* before a configurer is set
* added edge case protection
* tests
* added edge case test
* added tests
* added comment
* 100% coverage
* removed modifier onlyOwnerOrConfigurer
* Update utils/core-contracts/test/contracts/ownership/Configurable.test.ts
* audit refactor
---------
> SIP-341: Add Configurer Address (#2061)

- markets/perps-market/contracts/interfaces/IGlobalPerpsMarketModule.sol
- markets/perps-market/contracts/modules/GlobalPerpsMarketModule.sol
- markets/perps-market/contracts/storage/GlobalPerpsMarket.sol
- markets/perps-market/test/integration/Market/Market.minimumCredit.test.ts
- snxUSD is escrowed in the core system and is added to the credit capacity which is what is compared with minimumCredit to determine the capacity required for the market.
- in this PR, we account for this by adding the snxUSD owed to traders to minimumCredit
> Add snxUSD collateral to minCredit

- markets/bfp-market/contracts/storage/Position.sol
- Its added to `minimumCredit`, to align properly with core creditCapacity > minCredit
- So it needs to be added to our delegatedCollateralValue.
> sUSD collateral needs to be added

- protocol/oracle-manager/contracts/nodes/StalenessCircuitBreakerNode.sol
- protocol/oracle-manager/test/integration/nodes/StalenessCircuitBreakerNode.test.ts
On arbitrum sepolia block is minted with a reasonable delay so after getting the fresh price update txn - the timestamp of the update will be "in the future" for the current block and we get underflow error
Example: https://www.tdly.co/shared/simulation/8e997e25-04d6-47a9-b566-56a779efed4c
> Fix for underflow error when offchain price timestamp is bigger than current block timestamp

- markets/bfp-market/contracts/modules/MarginModule.sol
- markets/bfp-market/test/integration/modules/MarginModule.debt.test.ts
Updates `payDebt` function with `recomputeUtilization` becase the `amountToBurn` increases the creditCapacity of the market.
> Update payDebt with recomputeUtilization

- markets/legacy-market/cannonfile.toml
- markets/legacy-market/package.json
the contract in question can be deployed by any address since its accessed through a proxy, so the `from` address restriction should be removed
note: this has already been published/deployed
> legacy market: remove `from` restriction on contract deploy

- protocol/governance/cannonfile.arbitrum-sepolia.toml
- protocol/governance/cannonfile.optimistic-sepolia.toml
- protocol/governance/contracts/interfaces/ISnapshotVotePowerModule.sol
- protocol/governance/contracts/modules/core/SnapshotVotePowerModule.sol
- protocol/governance/contracts/storage/SnapshotVotePower.sol
- protocol/governance/contracts/utils/MathUtil.sol
- protocol/governance/storage.dump.sol
- protocol/governance/test/contracts/SnapshotVotePowerModule.test.ts
- protocol/governance/test/integration/CrossChainElections.test.ts
- protocol/governance/test/integration/Elections.test.ts
This PR adds the possibility to set how the voting power is calculated for the given snapshot contract balance. It defaults to the square root of the balance, which on previous versions was the default.
> Add voting power weight configuration

- markets/perps-market/contracts/modules/PerpsMarketFactoryModule.sol
- markets/perps-market/contracts/storage/AsyncOrder.sol
- markets/perps-market/contracts/storage/GlobalPerpsMarket.sol
- markets/perps-market/contracts/storage/PerpsMarket.sol
- markets/perps-market/test/integration/Insolvent.test.ts
- markets/perps-market/test/integration/Orders/Order.marginValidation.capped.test.ts
- markets/perps-market/test/integration/Orders/Order.marginValidation.test.ts
- markets/perps-market/test/integration/Orders/Order.marginWithPd.test.ts
- markets/perps-market/test/integration/Position/InterestRate.reset.test.ts
- markets/perps-market/test/integration/Position/InterestRate.test.ts
- markets/perps-market/test/integration/Position/InterestRate.tolerance.test.ts
- markets/perps-market/test/integration/helpers/requiredMargins.ts
> Various Perps v3 audit fixes

- markets/perps-market/contracts/modules/PerpsAccountModule.sol
- markets/perps-market/contracts/storage/PerpsAccount.sol
- markets/perps-market/test/integration/Account/PayDebt.test.ts
Some notable considerations:
- When `payDebt()` is called with an amount larger than the debt, only upto the debt amount is transferred from caller, so we have eliminated adding excess to USD margin since that would require global collateral validations and other considerations.
- All deposit/withdraw margin interactions are done via `modifyCollateral` for a trader.
- Only way to repay their debt is to call `payDebt`.
- Anyone can pay someone else's debt, no reason to have only trader pay their own debt
> PayDebt fixes

- markets/perps-market/contracts/storage/PerpsAccount.sol
make self-liquidate unprofitable by only allowing it if the account has outstanding debt
> Make self-liquidate non-profitable / C02

- markets/bfp-market/contracts/interfaces/IMarketConfigurationModule.sol
- markets/bfp-market/contracts/modules/MarketConfigurationModule.sol
- markets/bfp-market/test/integration/modules/MarketConfigurationModule.test.ts
Resolves an `onlyOwner` bug in previous PR https://github.com/Synthetixio/synthetix-v3/pull/2227, shuffles the fn definition to be grouped with mutations, and added new tests.
> fix: add OwnableStorage.onlyOwner and tests setMinDelegationTime

- utils/core-modules/package.json
According to @mjlescano, the `core-modules` package is imported via npm and isn't required to be built by cannon.
Currently breaking on main:
Steps to reproduce:
1. `git checkout main`
2. `cd utils/core-modules`
3. `yarn build`
> fix build script in core-modules

- .circleci/config.yml
- .github/dependabot.yml
1. Disable weekly cannon cache as it turns out to not be used by cannon when building testable and only getting big (few Gb) and slow, easily adding 2-3 min of unnecessary build time to `build-testable` step
2. Foundry has solved the issue and we can get back to using fresh version
3. Dependabot: add an "other" dependencies group excluding patterns from all other groups
> CI Improvements

- .github/workflows/cannon-update.yml
The idea is to let us easily trigger a cannon update to the `latest`, `hotfix` or `alpha` version and create a PR that will run all the CI tests. 
This should allow cannon devs to verify there are no breaking changes by doing alpha releases
> Cannon Update action

- protocol/synthetix/contracts/modules/core/RewardsManagerModule.sol
Prevents reverts on attempts to distribute rewards to an empty pool collateral.
Issue link:
https://www.notion.so/guardianaudits/M-21-1a8104646bc74f5abd6d35c8a3e6e096?pvs=4
> Fix to skip empty pool collateral distribution reverts

- markets/bfp-market/contracts/storage/Order.sol
**Description**
In the `getCancellationKeeperFee` and `getSettlementKeeperFee` functions the `keeperProfitMarginUsd` is not included in the consideration for the computed `baseKeeperFeePlusProfitUsd`.
This may be unexpected as the `getLiquidationFlagReward`, `getLiquidationKeeperFee` and `getMarginLiquidationOnlyReward` keeper fees include this static adjustment. In cases where the `baseKeeperFeeUsd` is small relative to the priority fee necessary to get the transaction recorded this can result in latent settlements and executions as the `keeperProfitMarginPercent` would not contribute as much as the static `keeperProfitMarginUsd` would have.
https://www.notion.so/guardianaudits/L-22-593481c4b88f42148cf4602e2734b51e?pvs=4
> Fix for L-22 issue

- protocol/synthetix/cannonfile.toml
- utils/common-config/hardhat.config.ts
random things I found while working on the repo
* turns out that for verification of USDProxy and AccountProxy, these contracts required UUPSProxyWithOwner instead of Proxy wrapper (verified this was case by manually verifying on etherscan)
* arbitrum mainnet was not included in hardhat networks spec
> misc fixes

- markets/perps-market/contracts/storage/PerpsAccount.sol
**Description**
`PerpsAccount.getPossibleLiquidationReward` computes the liquidation reward as `costOfLiquidation * (numOfWindows - 1)`.
There is a wrong assumption that the first liquidation window is already accounted for in the `liquidateAndFlagCost` variable.
It is wrong because when that variable is calculated, only `costOfFlagging` is passed to `keeperReward()` .
In result, the liquidation cost for the first window will not be added towards the total liquidation cost.
**Recommendation**
When calling `keeperReward()` to compute `liquidateAndFlagCost`, pass `costOfFlagging + costOfLiquidation` as second parameter.
> M-08: Liquidation rewards for first window is ignored

- markets/perps-market/contracts/modules/AsyncOrderSettlementPythModule.sol
**Description**
In the `_settleOrder` function the `MarketUpdated` event emits `runtime.sizeDelta` as the sizeDelta for the market, however this may be inaccurate for the market size when the order moves a position from long to short.
**Recommendation**
Consider whether the `sizeDelta` in the `MarketUpdated` should represent the change in market size or the change in position size. If it should represent the change in market size, then update the emitted value to be the new market size - the original market size.
> L-01: Unexpected sizeDelta Emitted

- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/test/integration/storage/Market/Market.test.ts
this is a much more correct calculation for determining if capacity is sufficient or not.
Its good that this issue turned out to be so benign.
> when checking capacity locked, also add the deposited collateral value

- protocol/synthetix/contracts/interfaces/IMarketManagerModule.sol
- protocol/synthetix/contracts/interfaces/IPoolModule.sol
- protocol/synthetix/contracts/modules/core/MarketManagerModule.sol
- protocol/synthetix/contracts/modules/core/PoolModule.sol
- protocol/synthetix/contracts/storage/Market.sol
- protocol/synthetix/contracts/storage/Pool.sol
- protocol/synthetix/test/integration/modules/core/MarketManagerModule.test.ts
- protocol/synthetix/test/integration/modules/core/PoolModuleFundAdmin.test.ts
should make it much easier to understand the underlying computations that go behind capacity locked or similar issues in the future
also fixes credit capacity locking with deposited collateral issue.
> add some new read-only functions to market and pool

- markets/treasury-market/cannonfile.test.toml
- protocol/synthetix/contracts/interfaces/ICollateralConfigurationModule.sol
- protocol/synthetix/contracts/interfaces/ICollateralModule.sol
- protocol/synthetix/contracts/modules/core/CollateralConfigurationModule.sol
- protocol/synthetix/contracts/modules/core/CollateralModule.sol
- protocol/synthetix/contracts/modules/core/MarketCollateralModule.sol
- protocol/synthetix/test/integration/modules/core/CollateralConfigurationModule/CollateralConfigurationModule.config.test.ts
- utils/core-contracts/contracts/token/ERC20Helper.sol
ability to deprecate deposited collaterals and move them to a new system for claim. The owner of the contract can specify a deprecation target, and collateral will be sent to this target for further deprecation related processing outside of v3.
notes:
* once a collateral is deprecated, it is also automatically disabled, which will prevent further usage of it. It should never be re-enabled or configured again.
* the owner is expected to act rationally wrt to usage of deprecation (ex. do not use deprecated collaterals to fund markets which are actively needed for protocol operation)
> Collateral Deprecation
